# generated by gen_pairs.py; regenerate rather than edit
def method_list_append_0():
    xs = [1, 2]
    m0 = xs.append(3)


def method_list_clear_1():
    xs = [1, 2]
    m1 = xs.clear()


def method_list_copy_2():
    xs = [1, 2]
    m2 = xs.copy()


def method_list_count_3():
    xs = [1, 2]
    m3 = xs.count(1)


def method_list_extend_4():
    xs = [1, 2]
    m4 = xs.extend([2])


def method_list_index_5():
    xs = [1, 2]
    m5 = xs.index(1)


def method_list_insert_6():
    xs = [1, 2]
    m6 = xs.insert(0, 9)


def method_list_pop_7():
    xs = [1, 2]
    m7 = xs.pop()


def method_list_remove_8():
    xs = [1, 2]
    m8 = xs.remove(1)


def method_list_reverse_9():
    xs = [1, 2]
    m9 = xs.reverse()


def method_list_sort_10():
    xs = [1, 2]
    m10 = xs.sort()


def method_dict_clear_11():
    d = {"k": 1}
    m11 = d.clear()


def method_dict_copy_12():
    d = {"k": 1}
    m12 = d.copy()


def method_dict_get_13():
    d = {"k": 1}
    m13 = d.get("k")


def method_dict_items_14():
    d = {"k": 1}
    m14 = d.items()


def method_dict_keys_15():
    d = {"k": 1}
    m15 = d.keys()


def method_dict_pop_16():
    d = {"k": 1}
    m16 = d.pop("k")


def method_dict_setdefault_17():
    d = {"k": 1}
    m17 = d.setdefault("k", 1)


def method_dict_update_18():
    d = {"k": 1}
    m18 = d.update({})


def method_dict_values_19():
    d = {"k": 1}
    m19 = d.values()


def method_set_add_20():
    s = {1, 2}
    s2 = {2, 3}
    m20 = s.add(3)


def method_set_clear_21():
    s = {1, 2}
    s2 = {2, 3}
    m21 = s.clear()


def method_set_copy_22():
    s = {1, 2}
    s2 = {2, 3}
    m22 = s.copy()


def method_set_difference_23():
    s = {1, 2}
    s2 = {2, 3}
    m23 = s.difference(s2)


def method_set_discard_24():
    s = {1, 2}
    s2 = {2, 3}
    m24 = s.discard(1)


def method_set_intersection_25():
    s = {1, 2}
    s2 = {2, 3}
    m25 = s.intersection(s2)


def method_set_isdisjoint_26():
    s = {1, 2}
    s2 = {2, 3}
    m26 = s.isdisjoint(s2)


def method_set_issubset_27():
    s = {1, 2}
    s2 = {2, 3}
    m27 = s.issubset(s2)


def method_set_issuperset_28():
    s = {1, 2}
    s2 = {2, 3}
    m28 = s.issuperset(s2)


def method_set_pop_29():
    s = {1, 2}
    s2 = {2, 3}
    m29 = s.pop()


def method_set_remove_30():
    s = {1, 2}
    s2 = {2, 3}
    m30 = s.remove(1)


def method_set_symmetric_difference_31():
    s = {1, 2}
    s2 = {2, 3}
    m31 = s.symmetric_difference(s2)


def method_set_union_32():
    s = {1, 2}
    s2 = {2, 3}
    m32 = s.union(s2)


def method_set_update_33():
    s = {1, 2}
    s2 = {2, 3}
    m33 = s.update(s2)


def method_tuple_count_34():
    t = (1, 2)
    m34 = t.count(1)


def method_tuple_index_35():
    t = (1, 2)
    m35 = t.index(1)


def method_range_count_36():
    rg = range(4)
    m36 = rg.count(1)


def method_range_index_37():
    rg = range(4)
    m37 = rg.index(1)


def method_str_capitalize_38():
    w = "aWb,c"
    m38 = w.capitalize()


def method_str_casefold_39():
    w = "aWb,c"
    m39 = w.casefold()


def method_str_center_40():
    w = "aWb,c"
    m40 = w.center(9)


def method_str_count_41():
    w = "aWb,c"
    m41 = w.count("a")


def method_str_endswith_42():
    w = "aWb,c"
    m42 = w.endswith("a")


def method_str_expandtabs_43():
    w = "aWb,c"
    m43 = w.expandtabs()


def method_str_find_44():
    w = "aWb,c"
    m44 = w.find("a")


def method_str_format_45():
    w = "aWb,c"
    m45 = w.format()


def method_str_index_46():
    w = "aWb,c"
    m46 = w.index("a")


def method_str_isalnum_47():
    w = "aWb,c"
    m47 = w.isalnum()


def method_str_isalpha_48():
    w = "aWb,c"
    m48 = w.isalpha()


def method_str_isascii_49():
    w = "aWb,c"
    m49 = w.isascii()


def method_str_isdecimal_50():
    w = "aWb,c"
    m50 = w.isdecimal()


def method_str_isdigit_51():
    w = "aWb,c"
    m51 = w.isdigit()


def method_str_isidentifier_52():
    w = "aWb,c"
    m52 = w.isidentifier()


def method_str_islower_53():
    w = "aWb,c"
    m53 = w.islower()


def method_str_isnumeric_54():
    w = "aWb,c"
    m54 = w.isnumeric()


def method_str_isprintable_55():
    w = "aWb,c"
    m55 = w.isprintable()


def method_str_isspace_56():
    w = "aWb,c"
    m56 = w.isspace()


def method_str_istitle_57():
    w = "aWb,c"
    m57 = w.istitle()


def method_str_isupper_58():
    w = "aWb,c"
    m58 = w.isupper()


def method_str_join_59():
    w = "aWb,c"
    m59 = w.join(["x"])


def method_str_ljust_60():
    w = "aWb,c"
    m60 = w.ljust(9)


def method_str_lower_61():
    w = "aWb,c"
    m61 = w.lower()


def method_str_lstrip_62():
    w = "aWb,c"
    m62 = w.lstrip()


def method_str_removeprefix_63():
    w = "aWb,c"
    m63 = w.removeprefix("a")


def method_str_removesuffix_64():
    w = "aWb,c"
    m64 = w.removesuffix("b")


def method_str_replace_65():
    w = "aWb,c"
    m65 = w.replace("a", "b")


def method_str_rfind_66():
    w = "aWb,c"
    m66 = w.rfind("a")


def method_str_rindex_67():
    w = "aWb,c"
    m67 = w.rindex("a")


def method_str_rjust_68():
    w = "aWb,c"
    m68 = w.rjust(9)


def method_str_rsplit_69():
    w = "aWb,c"
    m69 = w.rsplit(",")


def method_str_rstrip_70():
    w = "aWb,c"
    m70 = w.rstrip()


def method_str_split_71():
    w = "aWb,c"
    m71 = w.split(",")


def method_str_splitlines_72():
    w = "aWb,c"
    m72 = w.splitlines()


def method_str_startswith_73():
    w = "aWb,c"
    m73 = w.startswith("a")


def method_str_strip_74():
    w = "aWb,c"
    m74 = w.strip()


def method_str_swapcase_75():
    w = "aWb,c"
    m75 = w.swapcase()


def method_str_title_76():
    w = "aWb,c"
    m76 = w.title()


def method_str_upper_77():
    w = "aWb,c"
    m77 = w.upper()


def method_str_zfill_78():
    w = "aWb,c"
    m78 = w.zfill(4)
