# generated by gen_pairs.py; regenerate rather than edit
def list_modeled():
    xs = [1, 2]
    m1 = xs.append(3)


def dict_modeled():
    d = {"k": 1}
    m2 = d.setdefault("k", 0)


def dict_opaque():
    d = {"k": 1}
    op1 = d.popitem()


def set_modeled():
    s = {1, 2}
    m3 = s.add(3)


def set_opaque():
    s = {1, 2}
    xs = [1, 2]
    op2 = s.difference_update(xs)


def str_modeled():
    t = "ab,cd"
    m4 = t.split(",")


def str_opaque():
    t = "ab,cd"
    op3 = t.partition(",")


def list_absent():
    xs = [1, 2]
    ab1 = xs.no_such_method()


def dict_absent():
    d = {"k": 1}
    ab2 = d.no_such_method()


def str_absent():
    t = "ab,cd"
    ab3 = t.no_such_method()


def deferred_method():
    d = {"k": 1}
    op1 = d.popitem()
    dfr = op1.mystery_method()


def deferred_binary():
    d = {"k": 1}
    op1 = d.popitem()
    dfb = op1 + 1
