name = "StrataPython"
version = "0.1.0"
defaultTargets = ["StrataPython"]
testDriver = "StrataTestMain"

[[require]]
name = "Strata"
git = "https://github.com/strata-org/Strata.git"
rev = "main"

[[input_file]]
name = "PythonDialectIon"
path = "Tools/strata-python/dialects/Python.dialect.st.ion"
text = true

[[lean_lib]]
name = "StrataPython"
extraDepTargets = ["PythonDialectIon"]

[[lean_lib]]
name = "StrataPythonTest"
globs = ["StrataPythonTest.+"]

[[lean_lib]]
name = "StrataPythonTestExtra"
globs = ["StrataPythonTestExtra.+"]

[[lean_exe]]
name = "StrataTestMain"
needs = ["StrataPython", "StrataPythonTest"]

[[lean_exe]]
name = "DiffTestCore"
needs = ["StrataPython"]

[[lean_exe]]
name = "pyAnalyzeLaurel"
root = "Scripts.pyAnalyzeLaurel"
needs = ["StrataPython"]

[[lean_exe]]
name = "pyAnalyzeToGoto"
root = "Scripts.pyAnalyzeToGoto"
needs = ["StrataPython"]

[[lean_exe]]
name = "pyTranslateLaurel"
root = "Scripts.pyTranslateLaurel"
needs = ["StrataPython"]

[[lean_exe]]
name = "pyAnalyzeLaurelToGoto"
root = "Scripts.pyAnalyzeLaurelToGoto"
needs = ["StrataPython"]

[[lean_exe]]
name = "pySpecToLaurel"
root = "Scripts.pySpecToLaurel"
needs = ["StrataPython"]

[[lean_exe]]
name = "pyResolveOverloads"
root = "Scripts.pyResolveOverloads"
needs = ["StrataPython"]

[[lean_exe]]
name = "pyInterpret"
root = "Scripts.pyInterpret"
needs = ["StrataPython"]

[[lean_exe]]
name = "pySpecs"
root = "Scripts.pySpecs"
needs = ["StrataPython"]
