# generated by gen_pairs.py; regenerate rather than edit
xs = [3, 1]
n = len(xs)
rg = range(3)
print(n)
b = isinstance(xs, list)
it = iter(xs)
nx = next(it, 0)
l2 = list(rg)
t2 = tuple(xs)
s2 = set(xs)
d2 = dict()
sr = str(n)
rp = repr(xs)
