# Generated PyHard analysis. Original source line numbers are shown as L<n>.
# Every dispatch/type/shape claim lowers to assert followed by the same assume.
# Canonical machine-readable input: pyhard.analysis schema v1.
# L1 pyhard[summary first] returns={bool, int}; escapes={IndexError}
# L1 pyhard[type parameter] assert/assume conforms(values, list[int]); boundary nondet over 17 closed tags
def first(values: list[int]) -> int:
    # L2 pyhard[flow first in] values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure})
    # L2 pyhard[flow first out:raise:IndexError] $exception -> (binding=definitely_bound; tags={IndexError}; defs={raise:IndexError}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure})
    # L2 pyhard[flow first out:return] $result -> (binding=definitely_bound; tags={bool, int}; defs={return}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure})
    # L2 pyhard[read first.values@12] binding=definitely_bound
    # L2 pyhard[type return] assert/assume conforms(result, int); observed={bool, int}; evaluation may raise={IndexError}
    # L2 pyhard[type subscript_key] assert/assume conforms(0, int | slice); observed={int}
    # L2 pyhard[dispatch values[0]] assert/assume key in {list}
    # L2 pyhard[row {list}] exact_list; result={bool, int}; raises={IndexError}; specialized-by=index and recursive type contracts
    return values[0]


# L5 pyhard[summary collect_or_unbound] returns={list}; escapes={UnboundLocalError}
# L5 pyhard[type parameter] assert/assume conforms(groups, list[list[int]]); boundary nondet over 17 closed tags
def collect_or_unbound(groups: list[list[int]]) -> list[int]:
    # L6 pyhard[flow collect_or_unbound in] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result})
    # L6 pyhard[flow collect_or_unbound out] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L7:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L8:C5, unbound:missing}), result -> (binding=maybe_bound; tags={list}; defs={assignment:L7:C9, unbound:result}; points-to={alloc:L7:C18}); aliases may={group~groups, group~result, groups~result} must={}
    try:
        # L7 pyhard[flow collect_or_unbound in] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result})
        # L7 pyhard[flow collect_or_unbound out] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L7:C9}; points-to={alloc:L7:C18}); aliases may={groups~result} must={}
        # L7 pyhard[flow collect_or_unbound out:raise:IndexError] $exception -> (binding=definitely_bound; tags={IndexError}; defs={raise:IndexError}), group -> (binding=definitely_bound; tags={list}; defs={comprehension:L7:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}); aliases may={group~groups} must={}
        # L7 pyhard[read collect_or_unbound.groups@45] binding=definitely_bound
        # L7 pyhard[type call_argument] assert/assume conforms(values, list[int]); observed={list}
        # L7 pyhard[dispatch groups] assert/assume key in {list}
        # L7 pyhard[row {list}] call_iter; owner=list; label=builtins.list.__iter__; plan=[receiver.__iter__:builtins.list.__iter__]
        result = [first(group) for group in groups]
    except IndexError as missing:
        # L9 pyhard[flow collect_or_unbound in] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L7:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L8:C5}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}); aliases may={group~groups} must={}
        # L9 pyhard[flow collect_or_unbound out] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L7:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L8:C5}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}); aliases may={group~groups} must={}
        pass
    # L10 pyhard[flow collect_or_unbound in] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L7:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L8:C5, unbound:missing}), result -> (binding=maybe_bound; tags={list}; defs={assignment:L7:C9, unbound:result}; points-to={alloc:L7:C18}); aliases may={group~groups, group~result, groups~result} must={}
    # L10 pyhard[flow collect_or_unbound out:raise:UnboundLocalError] $exception -> (binding=definitely_bound; tags={UnboundLocalError}; defs={raise:UnboundLocalError}), group -> (binding=definitely_bound; tags={list}; defs={comprehension:L7:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L8:C5, unbound:missing}), result -> (binding=maybe_bound; tags={list}; defs={assignment:L7:C9, unbound:result}; points-to={alloc:L7:C18}); aliases may={group~groups, group~result, groups~result} must={}
    # L10 pyhard[flow collect_or_unbound out:return] $result -> (binding=definitely_bound; tags={list}; defs={return}), group -> (binding=definitely_bound; tags={list}; defs={comprehension:L7:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L8:C5, unbound:missing}), result -> (binding=maybe_bound; tags={list}; defs={assignment:L7:C9, unbound:result}; points-to={alloc:L7:C18}); aliases may={group~groups, group~result, groups~result} must={}
    # L10 pyhard[read collect_or_unbound.result@12] binding=maybe_bound; may raise UnboundLocalError
    # L10 pyhard[type return] assert/assume conforms(result, list[int]); observed={list}; evaluation may raise={UnboundLocalError}
    return result


# L13 pyhard[summary preserve_alias_on_failure] returns={list}; escapes={}
def preserve_alias_on_failure(
    # L14 pyhard[type parameter] assert/assume conforms(groups, list[list[int]]); boundary nondet over 17 closed tags
    groups: list[list[int]],
) -> list[int]:
    # L16 pyhard[flow preserve_alias_on_failure in] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_unbound; tags={}; defs={unbound:old}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result})
    # L16 pyhard[flow preserve_alias_on_failure out] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}); aliases may={groups~old} must={}
    old = [0]
    # L17 pyhard[flow preserve_alias_on_failure in] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}); aliases may={groups~old} must={}
    # L17 pyhard[flow preserve_alias_on_failure out] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5}; points-to={alloc:L16:C11}); aliases may={groups~old, groups~result, old~result} must={old~result}
    # L17 pyhard[read preserve_alias_on_failure.old@14] binding=definitely_bound
    result = old
    # L18 pyhard[flow preserve_alias_on_failure in] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5}; points-to={alloc:L16:C11}); aliases may={groups~old, groups~result, old~result} must={old~result}
    # L18 pyhard[flow preserve_alias_on_failure out] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L19:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L20:C5, unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5, assignment:L19:C9}; points-to={alloc:L16:C11, alloc:L19:C18}); aliases may={group~groups, group~old, group~result, groups~old, groups~result, old~result} must={}
    try:
        # L19 pyhard[flow preserve_alias_on_failure in] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5}; points-to={alloc:L16:C11}); aliases may={groups~old, groups~result, old~result} must={old~result}
        # L19 pyhard[flow preserve_alias_on_failure out] groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L19:C9}; points-to={alloc:L19:C18}); aliases may={groups~old, groups~result} must={}
        # L19 pyhard[flow preserve_alias_on_failure out:raise:IndexError] $exception -> (binding=definitely_bound; tags={IndexError}; defs={raise:IndexError}), group -> (binding=definitely_bound; tags={list}; defs={comprehension:L19:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5}; points-to={alloc:L16:C11}); aliases may={group~groups, group~old, group~result, groups~old, groups~result, old~result} must={old~result}
        # L19 pyhard[read preserve_alias_on_failure.groups@45] binding=definitely_bound
        # L19 pyhard[type call_argument] assert/assume conforms(values, list[int]); observed={list}
        # L19 pyhard[dispatch groups] assert/assume key in {list}
        # L19 pyhard[row {list}] call_iter; owner=list; label=builtins.list.__iter__; plan=[receiver.__iter__:builtins.list.__iter__]
        result = [first(group) for group in groups]
    except IndexError as missing:
        # L21 pyhard[flow preserve_alias_on_failure in] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L19:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L20:C5}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5}; points-to={alloc:L16:C11}); aliases may={group~groups, group~old, group~result, groups~old, groups~result, old~result} must={old~result}
        # L21 pyhard[flow preserve_alias_on_failure out] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L19:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L20:C5}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5}; points-to={alloc:L16:C11}); aliases may={group~groups, group~old, group~result, groups~old, groups~result, old~result} must={old~result}
        pass
    # L22 pyhard[flow preserve_alias_on_failure in] group -> (binding=definitely_bound; tags={list}; defs={comprehension:L19:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L20:C5, unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5, assignment:L19:C9}; points-to={alloc:L16:C11, alloc:L19:C18}); aliases may={group~groups, group~old, group~result, groups~old, groups~result, old~result} must={}
    # L22 pyhard[flow preserve_alias_on_failure out:return] $result -> (binding=definitely_bound; tags={list}; defs={return}), group -> (binding=definitely_bound; tags={list}; defs={comprehension:L19:C36}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), groups -> (binding=definitely_bound; tags={list}; defs={param:groups}; points-to={alloc:L16:C11, alloc:L19:C18, alloc:L7:C18, boundary:collect_or_unbound, boundary:external, boundary:first, boundary:preserve_alias_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L20:C5, unbound:missing}), old -> (binding=definitely_bound; tags={list}; defs={assignment:L16:C5}; points-to={alloc:L16:C11}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L17:C5, assignment:L19:C9}; points-to={alloc:L16:C11, alloc:L19:C18}); aliases may={group~groups, group~old, group~result, groups~old, groups~result, old~result} must={}
    # L22 pyhard[read preserve_alias_on_failure.result@12] binding=definitely_bound
    # L22 pyhard[type return] assert/assume conforms(result, list[int]); observed={list}
    return result
