# Generated PyHard analysis. Original source line numbers are shown as L<n>.
# Every dispatch/type/shape claim lowers to assert followed by the same assume.
# Canonical machine-readable input: pyhard.analysis schema v1.
# L1 pyhard[summary numeric_effects] returns={tuple}; escapes={OverflowError, ValueError, ZeroDivisionError}
def numeric_effects(
    # L2 pyhard[type parameter] assert/assume conforms(left, int); boundary nondet over 17 closed tags
    left: int,
    # L3 pyhard[type parameter] assert/assume conforms(right, int); boundary nondet over 17 closed tags
    right: int,
    # L4 pyhard[type parameter] assert/assume conforms(scale, float); boundary nondet over 17 closed tags
    scale: float,
    # L5 pyhard[type parameter] assert/assume conforms(shift, int); boundary nondet over 17 closed tags
    shift: int,
) -> tuple[float, float, int, bool]:
    # L7 pyhard[flow numeric_effects in] flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_unbound; tags={}; defs={unbound:mixed}), quotient -> (binding=definitely_unbound; tags={}; defs={unbound:quotient}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L7 pyhard[flow numeric_effects out] flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_unbound; tags={}; defs={unbound:mixed}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L7 pyhard[flow numeric_effects out:raise:OverflowError] $exception -> (binding=definitely_bound; tags={OverflowError}; defs={raise:OverflowError}), flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_unbound; tags={}; defs={unbound:mixed}), quotient -> (binding=definitely_unbound; tags={}; defs={unbound:quotient}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L7 pyhard[flow numeric_effects out:raise:ZeroDivisionError] $exception -> (binding=definitely_bound; tags={ZeroDivisionError}; defs={raise:ZeroDivisionError}), flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_unbound; tags={}; defs={unbound:mixed}), quotient -> (binding=definitely_unbound; tags={}; defs={unbound:quotient}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L7 pyhard[read numeric_effects.left@16] binding=definitely_bound
    # L7 pyhard[read numeric_effects.right@23] binding=definitely_bound
    # L7 pyhard[dispatch left / right] assert/assume key in {(bool, bool), (bool, int), (int, bool), (int, int)}
    # L7 pyhard[row {(bool, bool), (bool, int)}] binary_protocol; result={float}; raises={ZeroDivisionError}; terminal=certified_builtin_partial
    # L7 pyhard[row {(int, bool), (int, int)}] binary_protocol; result={float}; raises={OverflowError, ZeroDivisionError}; terminal=certified_builtin_partial
    quotient = left / right
    # L8 pyhard[flow numeric_effects in] flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_unbound; tags={}; defs={unbound:mixed}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L8 pyhard[flow numeric_effects out] flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L8 pyhard[flow numeric_effects out:raise:OverflowError] $exception -> (binding=definitely_bound; tags={OverflowError}; defs={raise:OverflowError}), flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_unbound; tags={}; defs={unbound:mixed}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L8 pyhard[read numeric_effects.left@13] binding=definitely_bound
    # L8 pyhard[read numeric_effects.scale@20] binding=definitely_bound
    # L8 pyhard[dispatch left + scale] assert/assume key in {(bool, bool), (bool, float), (bool, int), (int, bool), (int, float), (int, int)}
    # L8 pyhard[row {(bool, bool), (bool, int), (int, bool), (int, int)}] binary_protocol; result={int}; terminal=certified_builtin_total
    # L8 pyhard[row {(bool, float)}] binary_protocol; result={float}; terminal=certified_builtin_total
    # L8 pyhard[row {(int, float)}] binary_protocol; result={float}; raises={OverflowError}; terminal=certified_builtin_partial
    mixed = left + scale
    # L9 pyhard[flow numeric_effects in] flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L9 pyhard[flow numeric_effects out] flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_bound; tags={int}; defs={assignment:L9:C5})
    # L9 pyhard[flow numeric_effects out:raise:OverflowError] $exception -> (binding=definitely_bound; tags={OverflowError}; defs={raise:OverflowError}), flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L9 pyhard[flow numeric_effects out:raise:ValueError] $exception -> (binding=definitely_bound; tags={ValueError}; defs={raise:ValueError}), flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_unbound; tags={}; defs={unbound:shifted})
    # L9 pyhard[read numeric_effects.left@15] binding=definitely_bound
    # L9 pyhard[read numeric_effects.shift@23] binding=definitely_bound
    # L9 pyhard[dispatch left << shift] assert/assume key in {(bool, bool), (bool, int), (int, bool), (int, int)}
    # L9 pyhard[row {(bool, bool), (int, bool)}] binary_protocol; result={int}; terminal=certified_builtin_total
    # L9 pyhard[row {(bool, int), (int, int)}] binary_protocol; result={int}; raises={OverflowError, ValueError}; terminal=certified_builtin_partial
    shifted = left << shift
    # L10 pyhard[flow numeric_effects in] flags -> (binding=definitely_unbound; tags={}; defs={unbound:flags}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_bound; tags={int}; defs={assignment:L9:C5})
    # L10 pyhard[flow numeric_effects out] flags -> (binding=definitely_bound; tags={bool}; defs={assignment:L10:C5}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_bound; tags={int}; defs={assignment:L9:C5})
    # L10 pyhard[dispatch True & False] assert/assume key in {(bool, bool)}
    # L10 pyhard[row {(bool, bool)}] binary_protocol; result={bool}; terminal=certified_builtin_total
    flags = True & False
    # L11 pyhard[flow numeric_effects in] flags -> (binding=definitely_bound; tags={bool}; defs={assignment:L10:C5}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_bound; tags={int}; defs={assignment:L9:C5})
    # L11 pyhard[flow numeric_effects out:return] $result -> (binding=definitely_bound; tags={tuple}; defs={return}), flags -> (binding=definitely_bound; tags={bool}; defs={assignment:L10:C5}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), mixed -> (binding=definitely_bound; tags={float, int}; defs={assignment:L8:C5}), quotient -> (binding=definitely_bound; tags={float}; defs={assignment:L7:C5}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), scale -> (binding=definitely_bound; tags={bool, float, int}; defs={param:scale}), shift -> (binding=definitely_bound; tags={bool, int}; defs={param:shift}), shifted -> (binding=definitely_bound; tags={int}; defs={assignment:L9:C5})
    # L11 pyhard[read numeric_effects.quotient@12] binding=definitely_bound
    # L11 pyhard[read numeric_effects.mixed@22] binding=definitely_bound
    # L11 pyhard[read numeric_effects.shifted@29] binding=definitely_bound
    # L11 pyhard[read numeric_effects.flags@38] binding=definitely_bound
    # L11 pyhard[type return] assert/assume conforms(result, tuple[float, float, int, bool]); observed={tuple}
    return quotient, mixed, shifted, flags


# L14 pyhard[summary divide_or_zero] returns={float}; escapes={OverflowError}
# L14 pyhard[type parameter] assert/assume conforms(left, int); boundary nondet over 17 closed tags
# L14 pyhard[type parameter] assert/assume conforms(right, int); boundary nondet over 17 closed tags
def divide_or_zero(left: int, right: int) -> float:
    # L15 pyhard[flow divide_or_zero in] left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_unbound; tags={}; defs={unbound:zero})
    # L15 pyhard[flow divide_or_zero out:raise:OverflowError] $exception -> (binding=definitely_bound; tags={OverflowError}; defs={raise:OverflowError}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_unbound; tags={}; defs={unbound:zero})
    # L15 pyhard[flow divide_or_zero out:return] $result -> (binding=definitely_bound; tags={float}; defs={return}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L17:C5, unbound:zero})
    try:
        # L16 pyhard[flow divide_or_zero in] left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_unbound; tags={}; defs={unbound:zero})
        # L16 pyhard[flow divide_or_zero out:raise:OverflowError] $exception -> (binding=definitely_bound; tags={OverflowError}; defs={raise:OverflowError}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_unbound; tags={}; defs={unbound:zero})
        # L16 pyhard[flow divide_or_zero out:raise:ZeroDivisionError] $exception -> (binding=definitely_bound; tags={ZeroDivisionError}; defs={raise:ZeroDivisionError}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_unbound; tags={}; defs={unbound:zero})
        # L16 pyhard[flow divide_or_zero out:return] $result -> (binding=definitely_bound; tags={float}; defs={return}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_unbound; tags={}; defs={unbound:zero})
        # L16 pyhard[read divide_or_zero.left@16] binding=definitely_bound
        # L16 pyhard[read divide_or_zero.right@23] binding=definitely_bound
        # L16 pyhard[type return] assert/assume conforms(result, float); observed={float}; evaluation may raise={OverflowError, ZeroDivisionError}
        # L16 pyhard[dispatch left / right] assert/assume key in {(bool, bool), (bool, int), (int, bool), (int, int)}
        # L16 pyhard[row {(bool, bool), (bool, int)}] binary_protocol; result={float}; raises={ZeroDivisionError}; terminal=certified_builtin_partial
        # L16 pyhard[row {(int, bool), (int, int)}] binary_protocol; result={float}; raises={OverflowError, ZeroDivisionError}; terminal=certified_builtin_partial
        return left / right
    except ZeroDivisionError as zero:
        # L18 pyhard[flow divide_or_zero in] left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_bound; tags={ZeroDivisionError}; defs={handler:L17:C5})
        # L18 pyhard[flow divide_or_zero out:return] $result -> (binding=definitely_bound; tags={float}; defs={return}), left -> (binding=definitely_bound; tags={bool, int}; defs={param:left}), right -> (binding=definitely_bound; tags={bool, int}; defs={param:right}), zero -> (binding=definitely_bound; tags={ZeroDivisionError}; defs={handler:L17:C5})
        # L18 pyhard[type return] assert/assume conforms(result, float); observed={float}
        return 0.0
