# `@dataclass(order=True)` generates comparison methods — PLt/PGt on
# ClassInstance has no dispatch case; valid comparisons produce Hole
"""
@dataclass(order=True) GENERATES COMPARISON METHODS — MODEL DOESN'T KNOW

DIVERGENCE:
  CPython:  @dataclass(order=True) generates __lt__, __le__, __gt__, __ge__
            that compare instances field-by-field in declaration order.
            `Point(1, 2) < Point(1, 3)` → True (compares x first, then y).
  Model:    PLt on from_ClassInstance has no case for ordered dataclasses.
            Falls to catch-all → Hole or TypeError exception.
            The comparison SHOULD succeed but the model rejects it.

This is the OPPOSITE of finding 318 (which shows that comparison on
non-ordered dataclass should FAIL but model gives Hole). Here, comparison
on ordered dataclass should SUCCEED but model gives Hole/exception.

@dataclass is IN the subset. order=True is a standard parameter.
mypy --strict accepts ordered dataclass comparisons.

ROOT CAUSE: The model has no mechanism to dispatch comparison operators
to generated methods. PLt pattern-matches on tags (int, float, str) but
has no case for ClassInstance with order=True.
"""
from dataclasses import dataclass


@dataclass(order=True)
class Priority:
    level: int
    name: str


@dataclass(order=True)
class Version:
    major: int
    minor: int
    patch: int


def compare_priorities(a: Priority, b: Priority) -> bool:
    """Ordered dataclass comparison — field-by-field."""
    # CPython: compares level first, then name (lexicographic on fields)
    # Model: PLt(from_ClassInstance(...), from_ClassInstance(...)) → Hole
    return a < b


def sort_versions(versions: list[Version]) -> list[Version]:
    """Use ordering to find min/max."""
    # Can't use list.sort() (mutating), but can do manual min-finding
    if len(versions) == 0:
        return []
    result: list[Version] = []
    for v in versions:
        result.append(v)
    # Manual bubble-sort-like comparison
    return result


def find_max_version(versions: list[Version]) -> Version:
    """Find maximum version using > comparison."""
    best: Version = versions[0]
    for v in versions:
        if v > best:  # CPython: works. Model: Hole.
            best = v
    return best


def version_in_range(v: Version, low: Version, high: Version) -> bool:
    """Check if version is in range [low, high]."""
    # CPython: uses __le__ and __ge__ generated by order=True
    # Model: PLe/PGe on ClassInstance → Hole
    return low <= v and v <= high


def priority_ordering() -> bool:
    """Field-by-field ordering: first field dominates."""
    p1: Priority = Priority(level=1, name="low")
    p2: Priority = Priority(level=2, name="high")
    p3: Priority = Priority(level=1, name="medium")

    # level=1 < level=2 regardless of name
    assert p1 < p2

    # Same level: compare name lexicographically
    # "low" < "medium" (lexicographic)
    assert p1 < p3

    return True


def main() -> None:
    # Test 1: basic comparison
    assert compare_priorities(
        Priority(1, "a"), Priority(2, "b")
    ) == True
    assert compare_priorities(
        Priority(2, "a"), Priority(1, "b")
    ) == False

    # Test 2: field-by-field ordering
    assert priority_ordering()

    # Test 3: version comparison
    v1: Version = Version(1, 0, 0)
    v2: Version = Version(1, 2, 0)
    v3: Version = Version(2, 0, 0)

    assert find_max_version([v1, v2, v3]) == v3

    # Test 4: range check
    assert version_in_range(v2, v1, v3) == True
    assert version_in_range(v1, v2, v3) == False

    print("all passed")


main()
