# generated by gen_pairs.py; regenerate rather than edit
def matrix_add_0():
    c0 = 3 + 3


def matrix_add_1():
    c1 = 3 + 1.5


def matrix_add_2():
    c2 = 3 + True


def matrix_add_3():
    c3 = 3 + "ab"


def matrix_add_4():
    c4 = 3 + [1]


def matrix_add_5():
    c5 = 3 + (1,)


def matrix_add_6():
    c6 = 3 + {1}


def matrix_add_7():
    c7 = 3 + {"k": 1}


def matrix_add_8():
    c8 = 3 + None


def matrix_add_9():
    c9 = 1.5 + 3


def matrix_add_10():
    c10 = 1.5 + 1.5


def matrix_add_11():
    c11 = 1.5 + True


def matrix_add_12():
    c12 = 1.5 + "ab"


def matrix_add_13():
    c13 = 1.5 + [1]


def matrix_add_14():
    c14 = 1.5 + (1,)


def matrix_add_15():
    c15 = 1.5 + {1}


def matrix_add_16():
    c16 = 1.5 + {"k": 1}


def matrix_add_17():
    c17 = 1.5 + None


def matrix_add_18():
    c18 = True + 3


def matrix_add_19():
    c19 = True + 1.5


def matrix_add_20():
    c20 = True + True


def matrix_add_21():
    c21 = True + "ab"


def matrix_add_22():
    c22 = True + [1]


def matrix_add_23():
    c23 = True + (1,)


def matrix_add_24():
    c24 = True + {1}


def matrix_add_25():
    c25 = True + {"k": 1}


def matrix_add_26():
    c26 = True + None


def matrix_add_27():
    c27 = "ab" + 3


def matrix_add_28():
    c28 = "ab" + 1.5


def matrix_add_29():
    c29 = "ab" + True


def matrix_add_30():
    c30 = "ab" + "ab"


def matrix_add_31():
    c31 = "ab" + [1]


def matrix_add_32():
    c32 = "ab" + (1,)


def matrix_add_33():
    c33 = "ab" + {1}


def matrix_add_34():
    c34 = "ab" + {"k": 1}


def matrix_add_35():
    c35 = "ab" + None


def matrix_add_36():
    c36 = [1] + 3


def matrix_add_37():
    c37 = [1] + 1.5


def matrix_add_38():
    c38 = [1] + True


def matrix_add_39():
    c39 = [1] + "ab"


def matrix_add_40():
    c40 = [1] + [1]


def matrix_add_41():
    c41 = [1] + (1,)


def matrix_add_42():
    c42 = [1] + {1}


def matrix_add_43():
    c43 = [1] + {"k": 1}


def matrix_add_44():
    c44 = [1] + None


def matrix_add_45():
    c45 = (1,) + 3


def matrix_add_46():
    c46 = (1,) + 1.5


def matrix_add_47():
    c47 = (1,) + True


def matrix_add_48():
    c48 = (1,) + "ab"


def matrix_add_49():
    c49 = (1,) + [1]


def matrix_add_50():
    c50 = (1,) + (1,)


def matrix_add_51():
    c51 = (1,) + {1}


def matrix_add_52():
    c52 = (1,) + {"k": 1}


def matrix_add_53():
    c53 = (1,) + None


def matrix_add_54():
    c54 = {1} + 3


def matrix_add_55():
    c55 = {1} + 1.5


def matrix_add_56():
    c56 = {1} + True


def matrix_add_57():
    c57 = {1} + "ab"


def matrix_add_58():
    c58 = {1} + [1]


def matrix_add_59():
    c59 = {1} + (1,)


def matrix_add_60():
    c60 = {1} + {1}


def matrix_add_61():
    c61 = {1} + {"k": 1}


def matrix_add_62():
    c62 = {1} + None


def matrix_add_63():
    c63 = {"k": 1} + 3


def matrix_add_64():
    c64 = {"k": 1} + 1.5


def matrix_add_65():
    c65 = {"k": 1} + True


def matrix_add_66():
    c66 = {"k": 1} + "ab"


def matrix_add_67():
    c67 = {"k": 1} + [1]


def matrix_add_68():
    c68 = {"k": 1} + (1,)


def matrix_add_69():
    c69 = {"k": 1} + {1}


def matrix_add_70():
    c70 = {"k": 1} + {"k": 1}


def matrix_add_71():
    c71 = {"k": 1} + None


def matrix_add_72():
    c72 = None + 3


def matrix_add_73():
    c73 = None + 1.5


def matrix_add_74():
    c74 = None + True


def matrix_add_75():
    c75 = None + "ab"


def matrix_add_76():
    c76 = None + [1]


def matrix_add_77():
    c77 = None + (1,)


def matrix_add_78():
    c78 = None + {1}


def matrix_add_79():
    c79 = None + {"k": 1}


def matrix_add_80():
    c80 = None + None


def matrix_sub_81():
    c81 = 3 - 3


def matrix_sub_82():
    c82 = 3 - 1.5


def matrix_sub_83():
    c83 = 3 - True


def matrix_sub_84():
    c84 = 3 - "ab"


def matrix_sub_85():
    c85 = 3 - [1]


def matrix_sub_86():
    c86 = 3 - (1,)


def matrix_sub_87():
    c87 = 3 - {1}


def matrix_sub_88():
    c88 = 3 - {"k": 1}


def matrix_sub_89():
    c89 = 3 - None


def matrix_sub_90():
    c90 = 1.5 - 3


def matrix_sub_91():
    c91 = 1.5 - 1.5


def matrix_sub_92():
    c92 = 1.5 - True


def matrix_sub_93():
    c93 = 1.5 - "ab"


def matrix_sub_94():
    c94 = 1.5 - [1]


def matrix_sub_95():
    c95 = 1.5 - (1,)


def matrix_sub_96():
    c96 = 1.5 - {1}


def matrix_sub_97():
    c97 = 1.5 - {"k": 1}


def matrix_sub_98():
    c98 = 1.5 - None


def matrix_sub_99():
    c99 = True - 3


def matrix_sub_100():
    c100 = True - 1.5


def matrix_sub_101():
    c101 = True - True


def matrix_sub_102():
    c102 = True - "ab"


def matrix_sub_103():
    c103 = True - [1]


def matrix_sub_104():
    c104 = True - (1,)


def matrix_sub_105():
    c105 = True - {1}


def matrix_sub_106():
    c106 = True - {"k": 1}


def matrix_sub_107():
    c107 = True - None


def matrix_sub_108():
    c108 = "ab" - 3


def matrix_sub_109():
    c109 = "ab" - 1.5


def matrix_sub_110():
    c110 = "ab" - True


def matrix_sub_111():
    c111 = "ab" - "ab"


def matrix_sub_112():
    c112 = "ab" - [1]


def matrix_sub_113():
    c113 = "ab" - (1,)


def matrix_sub_114():
    c114 = "ab" - {1}


def matrix_sub_115():
    c115 = "ab" - {"k": 1}


def matrix_sub_116():
    c116 = "ab" - None


def matrix_sub_117():
    c117 = [1] - 3


def matrix_sub_118():
    c118 = [1] - 1.5


def matrix_sub_119():
    c119 = [1] - True


def matrix_sub_120():
    c120 = [1] - "ab"


def matrix_sub_121():
    c121 = [1] - [1]


def matrix_sub_122():
    c122 = [1] - (1,)


def matrix_sub_123():
    c123 = [1] - {1}


def matrix_sub_124():
    c124 = [1] - {"k": 1}


def matrix_sub_125():
    c125 = [1] - None


def matrix_sub_126():
    c126 = (1,) - 3


def matrix_sub_127():
    c127 = (1,) - 1.5


def matrix_sub_128():
    c128 = (1,) - True


def matrix_sub_129():
    c129 = (1,) - "ab"


def matrix_sub_130():
    c130 = (1,) - [1]


def matrix_sub_131():
    c131 = (1,) - (1,)


def matrix_sub_132():
    c132 = (1,) - {1}


def matrix_sub_133():
    c133 = (1,) - {"k": 1}


def matrix_sub_134():
    c134 = (1,) - None


def matrix_sub_135():
    c135 = {1} - 3


def matrix_sub_136():
    c136 = {1} - 1.5


def matrix_sub_137():
    c137 = {1} - True


def matrix_sub_138():
    c138 = {1} - "ab"


def matrix_sub_139():
    c139 = {1} - [1]


def matrix_sub_140():
    c140 = {1} - (1,)


def matrix_sub_141():
    c141 = {1} - {1}


def matrix_sub_142():
    c142 = {1} - {"k": 1}


def matrix_sub_143():
    c143 = {1} - None


def matrix_sub_144():
    c144 = {"k": 1} - 3


def matrix_sub_145():
    c145 = {"k": 1} - 1.5


def matrix_sub_146():
    c146 = {"k": 1} - True


def matrix_sub_147():
    c147 = {"k": 1} - "ab"


def matrix_sub_148():
    c148 = {"k": 1} - [1]


def matrix_sub_149():
    c149 = {"k": 1} - (1,)


def matrix_sub_150():
    c150 = {"k": 1} - {1}


def matrix_sub_151():
    c151 = {"k": 1} - {"k": 1}


def matrix_sub_152():
    c152 = {"k": 1} - None


def matrix_sub_153():
    c153 = None - 3


def matrix_sub_154():
    c154 = None - 1.5


def matrix_sub_155():
    c155 = None - True


def matrix_sub_156():
    c156 = None - "ab"


def matrix_sub_157():
    c157 = None - [1]


def matrix_sub_158():
    c158 = None - (1,)


def matrix_sub_159():
    c159 = None - {1}


def matrix_sub_160():
    c160 = None - {"k": 1}


def matrix_sub_161():
    c161 = None - None


def matrix_mul_162():
    c162 = 3 * 3


def matrix_mul_163():
    c163 = 3 * 1.5


def matrix_mul_164():
    c164 = 3 * True


def matrix_mul_165():
    c165 = 3 * "ab"


def matrix_mul_166():
    c166 = 3 * [1]


def matrix_mul_167():
    c167 = 3 * (1,)


def matrix_mul_168():
    c168 = 3 * {1}


def matrix_mul_169():
    c169 = 3 * {"k": 1}


def matrix_mul_170():
    c170 = 3 * None


def matrix_mul_171():
    c171 = 1.5 * 3


def matrix_mul_172():
    c172 = 1.5 * 1.5


def matrix_mul_173():
    c173 = 1.5 * True


def matrix_mul_174():
    c174 = 1.5 * "ab"


def matrix_mul_175():
    c175 = 1.5 * [1]


def matrix_mul_176():
    c176 = 1.5 * (1,)


def matrix_mul_177():
    c177 = 1.5 * {1}


def matrix_mul_178():
    c178 = 1.5 * {"k": 1}


def matrix_mul_179():
    c179 = 1.5 * None


def matrix_mul_180():
    c180 = True * 3


def matrix_mul_181():
    c181 = True * 1.5


def matrix_mul_182():
    c182 = True * True


def matrix_mul_183():
    c183 = True * "ab"


def matrix_mul_184():
    c184 = True * [1]


def matrix_mul_185():
    c185 = True * (1,)


def matrix_mul_186():
    c186 = True * {1}


def matrix_mul_187():
    c187 = True * {"k": 1}


def matrix_mul_188():
    c188 = True * None


def matrix_mul_189():
    c189 = "ab" * 3


def matrix_mul_190():
    c190 = "ab" * 1.5


def matrix_mul_191():
    c191 = "ab" * True


def matrix_mul_192():
    c192 = "ab" * "ab"


def matrix_mul_193():
    c193 = "ab" * [1]


def matrix_mul_194():
    c194 = "ab" * (1,)


def matrix_mul_195():
    c195 = "ab" * {1}


def matrix_mul_196():
    c196 = "ab" * {"k": 1}


def matrix_mul_197():
    c197 = "ab" * None


def matrix_mul_198():
    c198 = [1] * 3


def matrix_mul_199():
    c199 = [1] * 1.5


def matrix_mul_200():
    c200 = [1] * True


def matrix_mul_201():
    c201 = [1] * "ab"


def matrix_mul_202():
    c202 = [1] * [1]


def matrix_mul_203():
    c203 = [1] * (1,)


def matrix_mul_204():
    c204 = [1] * {1}


def matrix_mul_205():
    c205 = [1] * {"k": 1}


def matrix_mul_206():
    c206 = [1] * None


def matrix_mul_207():
    c207 = (1,) * 3


def matrix_mul_208():
    c208 = (1,) * 1.5


def matrix_mul_209():
    c209 = (1,) * True


def matrix_mul_210():
    c210 = (1,) * "ab"


def matrix_mul_211():
    c211 = (1,) * [1]


def matrix_mul_212():
    c212 = (1,) * (1,)


def matrix_mul_213():
    c213 = (1,) * {1}


def matrix_mul_214():
    c214 = (1,) * {"k": 1}


def matrix_mul_215():
    c215 = (1,) * None


def matrix_mul_216():
    c216 = {1} * 3


def matrix_mul_217():
    c217 = {1} * 1.5


def matrix_mul_218():
    c218 = {1} * True


def matrix_mul_219():
    c219 = {1} * "ab"


def matrix_mul_220():
    c220 = {1} * [1]


def matrix_mul_221():
    c221 = {1} * (1,)


def matrix_mul_222():
    c222 = {1} * {1}


def matrix_mul_223():
    c223 = {1} * {"k": 1}


def matrix_mul_224():
    c224 = {1} * None


def matrix_mul_225():
    c225 = {"k": 1} * 3


def matrix_mul_226():
    c226 = {"k": 1} * 1.5


def matrix_mul_227():
    c227 = {"k": 1} * True


def matrix_mul_228():
    c228 = {"k": 1} * "ab"


def matrix_mul_229():
    c229 = {"k": 1} * [1]


def matrix_mul_230():
    c230 = {"k": 1} * (1,)


def matrix_mul_231():
    c231 = {"k": 1} * {1}


def matrix_mul_232():
    c232 = {"k": 1} * {"k": 1}


def matrix_mul_233():
    c233 = {"k": 1} * None


def matrix_mul_234():
    c234 = None * 3


def matrix_mul_235():
    c235 = None * 1.5


def matrix_mul_236():
    c236 = None * True


def matrix_mul_237():
    c237 = None * "ab"


def matrix_mul_238():
    c238 = None * [1]


def matrix_mul_239():
    c239 = None * (1,)


def matrix_mul_240():
    c240 = None * {1}


def matrix_mul_241():
    c241 = None * {"k": 1}


def matrix_mul_242():
    c242 = None * None


def matrix_div_243():
    c243 = 3 / 3


def matrix_div_244():
    c244 = 3 / 1.5


def matrix_div_245():
    c245 = 3 / True


def matrix_div_246():
    c246 = 3 / "ab"


def matrix_div_247():
    c247 = 3 / [1]


def matrix_div_248():
    c248 = 3 / (1,)


def matrix_div_249():
    c249 = 3 / {1}


def matrix_div_250():
    c250 = 3 / {"k": 1}


def matrix_div_251():
    c251 = 3 / None


def matrix_div_252():
    c252 = 1.5 / 3


def matrix_div_253():
    c253 = 1.5 / 1.5


def matrix_div_254():
    c254 = 1.5 / True


def matrix_div_255():
    c255 = 1.5 / "ab"


def matrix_div_256():
    c256 = 1.5 / [1]


def matrix_div_257():
    c257 = 1.5 / (1,)


def matrix_div_258():
    c258 = 1.5 / {1}


def matrix_div_259():
    c259 = 1.5 / {"k": 1}


def matrix_div_260():
    c260 = 1.5 / None


def matrix_div_261():
    c261 = True / 3


def matrix_div_262():
    c262 = True / 1.5


def matrix_div_263():
    c263 = True / True


def matrix_div_264():
    c264 = True / "ab"


def matrix_div_265():
    c265 = True / [1]


def matrix_div_266():
    c266 = True / (1,)


def matrix_div_267():
    c267 = True / {1}


def matrix_div_268():
    c268 = True / {"k": 1}


def matrix_div_269():
    c269 = True / None


def matrix_div_270():
    c270 = "ab" / 3


def matrix_div_271():
    c271 = "ab" / 1.5


def matrix_div_272():
    c272 = "ab" / True


def matrix_div_273():
    c273 = "ab" / "ab"


def matrix_div_274():
    c274 = "ab" / [1]


def matrix_div_275():
    c275 = "ab" / (1,)


def matrix_div_276():
    c276 = "ab" / {1}


def matrix_div_277():
    c277 = "ab" / {"k": 1}


def matrix_div_278():
    c278 = "ab" / None


def matrix_div_279():
    c279 = [1] / 3


def matrix_div_280():
    c280 = [1] / 1.5


def matrix_div_281():
    c281 = [1] / True


def matrix_div_282():
    c282 = [1] / "ab"


def matrix_div_283():
    c283 = [1] / [1]


def matrix_div_284():
    c284 = [1] / (1,)


def matrix_div_285():
    c285 = [1] / {1}


def matrix_div_286():
    c286 = [1] / {"k": 1}


def matrix_div_287():
    c287 = [1] / None


def matrix_div_288():
    c288 = (1,) / 3


def matrix_div_289():
    c289 = (1,) / 1.5


def matrix_div_290():
    c290 = (1,) / True


def matrix_div_291():
    c291 = (1,) / "ab"


def matrix_div_292():
    c292 = (1,) / [1]


def matrix_div_293():
    c293 = (1,) / (1,)


def matrix_div_294():
    c294 = (1,) / {1}


def matrix_div_295():
    c295 = (1,) / {"k": 1}


def matrix_div_296():
    c296 = (1,) / None


def matrix_div_297():
    c297 = {1} / 3


def matrix_div_298():
    c298 = {1} / 1.5


def matrix_div_299():
    c299 = {1} / True


def matrix_div_300():
    c300 = {1} / "ab"


def matrix_div_301():
    c301 = {1} / [1]


def matrix_div_302():
    c302 = {1} / (1,)


def matrix_div_303():
    c303 = {1} / {1}


def matrix_div_304():
    c304 = {1} / {"k": 1}


def matrix_div_305():
    c305 = {1} / None


def matrix_div_306():
    c306 = {"k": 1} / 3


def matrix_div_307():
    c307 = {"k": 1} / 1.5


def matrix_div_308():
    c308 = {"k": 1} / True


def matrix_div_309():
    c309 = {"k": 1} / "ab"


def matrix_div_310():
    c310 = {"k": 1} / [1]


def matrix_div_311():
    c311 = {"k": 1} / (1,)


def matrix_div_312():
    c312 = {"k": 1} / {1}


def matrix_div_313():
    c313 = {"k": 1} / {"k": 1}


def matrix_div_314():
    c314 = {"k": 1} / None


def matrix_div_315():
    c315 = None / 3


def matrix_div_316():
    c316 = None / 1.5


def matrix_div_317():
    c317 = None / True


def matrix_div_318():
    c318 = None / "ab"


def matrix_div_319():
    c319 = None / [1]


def matrix_div_320():
    c320 = None / (1,)


def matrix_div_321():
    c321 = None / {1}


def matrix_div_322():
    c322 = None / {"k": 1}


def matrix_div_323():
    c323 = None / None


def matrix_floordiv_324():
    c324 = 3 // 3


def matrix_floordiv_325():
    c325 = 3 // 1.5


def matrix_floordiv_326():
    c326 = 3 // True


def matrix_floordiv_327():
    c327 = 3 // "ab"


def matrix_floordiv_328():
    c328 = 3 // [1]


def matrix_floordiv_329():
    c329 = 3 // (1,)


def matrix_floordiv_330():
    c330 = 3 // {1}


def matrix_floordiv_331():
    c331 = 3 // {"k": 1}


def matrix_floordiv_332():
    c332 = 3 // None


def matrix_floordiv_333():
    c333 = 1.5 // 3


def matrix_floordiv_334():
    c334 = 1.5 // 1.5


def matrix_floordiv_335():
    c335 = 1.5 // True


def matrix_floordiv_336():
    c336 = 1.5 // "ab"


def matrix_floordiv_337():
    c337 = 1.5 // [1]


def matrix_floordiv_338():
    c338 = 1.5 // (1,)


def matrix_floordiv_339():
    c339 = 1.5 // {1}


def matrix_floordiv_340():
    c340 = 1.5 // {"k": 1}


def matrix_floordiv_341():
    c341 = 1.5 // None


def matrix_floordiv_342():
    c342 = True // 3


def matrix_floordiv_343():
    c343 = True // 1.5


def matrix_floordiv_344():
    c344 = True // True


def matrix_floordiv_345():
    c345 = True // "ab"


def matrix_floordiv_346():
    c346 = True // [1]


def matrix_floordiv_347():
    c347 = True // (1,)


def matrix_floordiv_348():
    c348 = True // {1}


def matrix_floordiv_349():
    c349 = True // {"k": 1}


def matrix_floordiv_350():
    c350 = True // None


def matrix_floordiv_351():
    c351 = "ab" // 3


def matrix_floordiv_352():
    c352 = "ab" // 1.5


def matrix_floordiv_353():
    c353 = "ab" // True


def matrix_floordiv_354():
    c354 = "ab" // "ab"


def matrix_floordiv_355():
    c355 = "ab" // [1]


def matrix_floordiv_356():
    c356 = "ab" // (1,)


def matrix_floordiv_357():
    c357 = "ab" // {1}


def matrix_floordiv_358():
    c358 = "ab" // {"k": 1}


def matrix_floordiv_359():
    c359 = "ab" // None


def matrix_floordiv_360():
    c360 = [1] // 3


def matrix_floordiv_361():
    c361 = [1] // 1.5


def matrix_floordiv_362():
    c362 = [1] // True


def matrix_floordiv_363():
    c363 = [1] // "ab"


def matrix_floordiv_364():
    c364 = [1] // [1]


def matrix_floordiv_365():
    c365 = [1] // (1,)


def matrix_floordiv_366():
    c366 = [1] // {1}


def matrix_floordiv_367():
    c367 = [1] // {"k": 1}


def matrix_floordiv_368():
    c368 = [1] // None


def matrix_floordiv_369():
    c369 = (1,) // 3


def matrix_floordiv_370():
    c370 = (1,) // 1.5


def matrix_floordiv_371():
    c371 = (1,) // True


def matrix_floordiv_372():
    c372 = (1,) // "ab"


def matrix_floordiv_373():
    c373 = (1,) // [1]


def matrix_floordiv_374():
    c374 = (1,) // (1,)


def matrix_floordiv_375():
    c375 = (1,) // {1}


def matrix_floordiv_376():
    c376 = (1,) // {"k": 1}


def matrix_floordiv_377():
    c377 = (1,) // None


def matrix_floordiv_378():
    c378 = {1} // 3


def matrix_floordiv_379():
    c379 = {1} // 1.5


def matrix_floordiv_380():
    c380 = {1} // True


def matrix_floordiv_381():
    c381 = {1} // "ab"


def matrix_floordiv_382():
    c382 = {1} // [1]


def matrix_floordiv_383():
    c383 = {1} // (1,)


def matrix_floordiv_384():
    c384 = {1} // {1}


def matrix_floordiv_385():
    c385 = {1} // {"k": 1}


def matrix_floordiv_386():
    c386 = {1} // None


def matrix_floordiv_387():
    c387 = {"k": 1} // 3


def matrix_floordiv_388():
    c388 = {"k": 1} // 1.5


def matrix_floordiv_389():
    c389 = {"k": 1} // True


def matrix_floordiv_390():
    c390 = {"k": 1} // "ab"


def matrix_floordiv_391():
    c391 = {"k": 1} // [1]


def matrix_floordiv_392():
    c392 = {"k": 1} // (1,)


def matrix_floordiv_393():
    c393 = {"k": 1} // {1}


def matrix_floordiv_394():
    c394 = {"k": 1} // {"k": 1}


def matrix_floordiv_395():
    c395 = {"k": 1} // None


def matrix_floordiv_396():
    c396 = None // 3


def matrix_floordiv_397():
    c397 = None // 1.5


def matrix_floordiv_398():
    c398 = None // True


def matrix_floordiv_399():
    c399 = None // "ab"


def matrix_floordiv_400():
    c400 = None // [1]


def matrix_floordiv_401():
    c401 = None // (1,)


def matrix_floordiv_402():
    c402 = None // {1}


def matrix_floordiv_403():
    c403 = None // {"k": 1}


def matrix_floordiv_404():
    c404 = None // None


def matrix_mod_405():
    c405 = 3 % 3


def matrix_mod_406():
    c406 = 3 % 1.5


def matrix_mod_407():
    c407 = 3 % True


def matrix_mod_408():
    c408 = 3 % "ab"


def matrix_mod_409():
    c409 = 3 % [1]


def matrix_mod_410():
    c410 = 3 % (1,)


def matrix_mod_411():
    c411 = 3 % {1}


def matrix_mod_412():
    c412 = 3 % {"k": 1}


def matrix_mod_413():
    c413 = 3 % None


def matrix_mod_414():
    c414 = 1.5 % 3


def matrix_mod_415():
    c415 = 1.5 % 1.5


def matrix_mod_416():
    c416 = 1.5 % True


def matrix_mod_417():
    c417 = 1.5 % "ab"


def matrix_mod_418():
    c418 = 1.5 % [1]


def matrix_mod_419():
    c419 = 1.5 % (1,)


def matrix_mod_420():
    c420 = 1.5 % {1}


def matrix_mod_421():
    c421 = 1.5 % {"k": 1}


def matrix_mod_422():
    c422 = 1.5 % None


def matrix_mod_423():
    c423 = True % 3


def matrix_mod_424():
    c424 = True % 1.5


def matrix_mod_425():
    c425 = True % True


def matrix_mod_426():
    c426 = True % "ab"


def matrix_mod_427():
    c427 = True % [1]


def matrix_mod_428():
    c428 = True % (1,)


def matrix_mod_429():
    c429 = True % {1}


def matrix_mod_430():
    c430 = True % {"k": 1}


def matrix_mod_431():
    c431 = True % None


def matrix_mod_432():
    c432 = "ab" % 3


def matrix_mod_433():
    c433 = "ab" % 1.5


def matrix_mod_434():
    c434 = "ab" % True


def matrix_mod_435():
    c435 = "ab" % "ab"


def matrix_mod_436():
    c436 = "ab" % [1]


def matrix_mod_437():
    c437 = "ab" % (1,)


def matrix_mod_438():
    c438 = "ab" % {1}


def matrix_mod_439():
    c439 = "ab" % {"k": 1}


def matrix_mod_440():
    c440 = "ab" % None


def matrix_mod_441():
    c441 = [1] % 3


def matrix_mod_442():
    c442 = [1] % 1.5


def matrix_mod_443():
    c443 = [1] % True


def matrix_mod_444():
    c444 = [1] % "ab"


def matrix_mod_445():
    c445 = [1] % [1]


def matrix_mod_446():
    c446 = [1] % (1,)


def matrix_mod_447():
    c447 = [1] % {1}


def matrix_mod_448():
    c448 = [1] % {"k": 1}


def matrix_mod_449():
    c449 = [1] % None


def matrix_mod_450():
    c450 = (1,) % 3


def matrix_mod_451():
    c451 = (1,) % 1.5


def matrix_mod_452():
    c452 = (1,) % True


def matrix_mod_453():
    c453 = (1,) % "ab"


def matrix_mod_454():
    c454 = (1,) % [1]


def matrix_mod_455():
    c455 = (1,) % (1,)


def matrix_mod_456():
    c456 = (1,) % {1}


def matrix_mod_457():
    c457 = (1,) % {"k": 1}


def matrix_mod_458():
    c458 = (1,) % None


def matrix_mod_459():
    c459 = {1} % 3


def matrix_mod_460():
    c460 = {1} % 1.5


def matrix_mod_461():
    c461 = {1} % True


def matrix_mod_462():
    c462 = {1} % "ab"


def matrix_mod_463():
    c463 = {1} % [1]


def matrix_mod_464():
    c464 = {1} % (1,)


def matrix_mod_465():
    c465 = {1} % {1}


def matrix_mod_466():
    c466 = {1} % {"k": 1}


def matrix_mod_467():
    c467 = {1} % None


def matrix_mod_468():
    c468 = {"k": 1} % 3


def matrix_mod_469():
    c469 = {"k": 1} % 1.5


def matrix_mod_470():
    c470 = {"k": 1} % True


def matrix_mod_471():
    c471 = {"k": 1} % "ab"


def matrix_mod_472():
    c472 = {"k": 1} % [1]


def matrix_mod_473():
    c473 = {"k": 1} % (1,)


def matrix_mod_474():
    c474 = {"k": 1} % {1}


def matrix_mod_475():
    c475 = {"k": 1} % {"k": 1}


def matrix_mod_476():
    c476 = {"k": 1} % None


def matrix_mod_477():
    c477 = None % 3


def matrix_mod_478():
    c478 = None % 1.5


def matrix_mod_479():
    c479 = None % True


def matrix_mod_480():
    c480 = None % "ab"


def matrix_mod_481():
    c481 = None % [1]


def matrix_mod_482():
    c482 = None % (1,)


def matrix_mod_483():
    c483 = None % {1}


def matrix_mod_484():
    c484 = None % {"k": 1}


def matrix_mod_485():
    c485 = None % None


def matrix_pow_486():
    c486 = 3 ** 3


def matrix_pow_487():
    c487 = 3 ** 1.5


def matrix_pow_488():
    c488 = 3 ** True


def matrix_pow_489():
    c489 = 3 ** "ab"


def matrix_pow_490():
    c490 = 3 ** [1]


def matrix_pow_491():
    c491 = 3 ** (1,)


def matrix_pow_492():
    c492 = 3 ** {1}


def matrix_pow_493():
    c493 = 3 ** {"k": 1}


def matrix_pow_494():
    c494 = 3 ** None


def matrix_pow_495():
    c495 = 1.5 ** 3


def matrix_pow_496():
    c496 = 1.5 ** 1.5


def matrix_pow_497():
    c497 = 1.5 ** True


def matrix_pow_498():
    c498 = 1.5 ** "ab"


def matrix_pow_499():
    c499 = 1.5 ** [1]


def matrix_pow_500():
    c500 = 1.5 ** (1,)


def matrix_pow_501():
    c501 = 1.5 ** {1}


def matrix_pow_502():
    c502 = 1.5 ** {"k": 1}


def matrix_pow_503():
    c503 = 1.5 ** None


def matrix_pow_504():
    c504 = True ** 3


def matrix_pow_505():
    c505 = True ** 1.5


def matrix_pow_506():
    c506 = True ** True


def matrix_pow_507():
    c507 = True ** "ab"


def matrix_pow_508():
    c508 = True ** [1]


def matrix_pow_509():
    c509 = True ** (1,)


def matrix_pow_510():
    c510 = True ** {1}


def matrix_pow_511():
    c511 = True ** {"k": 1}


def matrix_pow_512():
    c512 = True ** None


def matrix_pow_513():
    c513 = "ab" ** 3


def matrix_pow_514():
    c514 = "ab" ** 1.5


def matrix_pow_515():
    c515 = "ab" ** True


def matrix_pow_516():
    c516 = "ab" ** "ab"


def matrix_pow_517():
    c517 = "ab" ** [1]


def matrix_pow_518():
    c518 = "ab" ** (1,)


def matrix_pow_519():
    c519 = "ab" ** {1}


def matrix_pow_520():
    c520 = "ab" ** {"k": 1}


def matrix_pow_521():
    c521 = "ab" ** None


def matrix_pow_522():
    c522 = [1] ** 3


def matrix_pow_523():
    c523 = [1] ** 1.5


def matrix_pow_524():
    c524 = [1] ** True


def matrix_pow_525():
    c525 = [1] ** "ab"


def matrix_pow_526():
    c526 = [1] ** [1]


def matrix_pow_527():
    c527 = [1] ** (1,)


def matrix_pow_528():
    c528 = [1] ** {1}


def matrix_pow_529():
    c529 = [1] ** {"k": 1}


def matrix_pow_530():
    c530 = [1] ** None


def matrix_pow_531():
    c531 = (1,) ** 3


def matrix_pow_532():
    c532 = (1,) ** 1.5


def matrix_pow_533():
    c533 = (1,) ** True


def matrix_pow_534():
    c534 = (1,) ** "ab"


def matrix_pow_535():
    c535 = (1,) ** [1]


def matrix_pow_536():
    c536 = (1,) ** (1,)


def matrix_pow_537():
    c537 = (1,) ** {1}


def matrix_pow_538():
    c538 = (1,) ** {"k": 1}


def matrix_pow_539():
    c539 = (1,) ** None


def matrix_pow_540():
    c540 = {1} ** 3


def matrix_pow_541():
    c541 = {1} ** 1.5


def matrix_pow_542():
    c542 = {1} ** True


def matrix_pow_543():
    c543 = {1} ** "ab"


def matrix_pow_544():
    c544 = {1} ** [1]


def matrix_pow_545():
    c545 = {1} ** (1,)


def matrix_pow_546():
    c546 = {1} ** {1}


def matrix_pow_547():
    c547 = {1} ** {"k": 1}


def matrix_pow_548():
    c548 = {1} ** None


def matrix_pow_549():
    c549 = {"k": 1} ** 3


def matrix_pow_550():
    c550 = {"k": 1} ** 1.5


def matrix_pow_551():
    c551 = {"k": 1} ** True


def matrix_pow_552():
    c552 = {"k": 1} ** "ab"


def matrix_pow_553():
    c553 = {"k": 1} ** [1]


def matrix_pow_554():
    c554 = {"k": 1} ** (1,)


def matrix_pow_555():
    c555 = {"k": 1} ** {1}


def matrix_pow_556():
    c556 = {"k": 1} ** {"k": 1}


def matrix_pow_557():
    c557 = {"k": 1} ** None


def matrix_pow_558():
    c558 = None ** 3


def matrix_pow_559():
    c559 = None ** 1.5


def matrix_pow_560():
    c560 = None ** True


def matrix_pow_561():
    c561 = None ** "ab"


def matrix_pow_562():
    c562 = None ** [1]


def matrix_pow_563():
    c563 = None ** (1,)


def matrix_pow_564():
    c564 = None ** {1}


def matrix_pow_565():
    c565 = None ** {"k": 1}


def matrix_pow_566():
    c566 = None ** None


def matrix_lshift_567():
    c567 = 3 << 3


def matrix_lshift_568():
    c568 = 3 << 1.5


def matrix_lshift_569():
    c569 = 3 << True


def matrix_lshift_570():
    c570 = 3 << "ab"


def matrix_lshift_571():
    c571 = 3 << [1]


def matrix_lshift_572():
    c572 = 3 << (1,)


def matrix_lshift_573():
    c573 = 3 << {1}


def matrix_lshift_574():
    c574 = 3 << {"k": 1}


def matrix_lshift_575():
    c575 = 3 << None


def matrix_lshift_576():
    c576 = 1.5 << 3


def matrix_lshift_577():
    c577 = 1.5 << 1.5


def matrix_lshift_578():
    c578 = 1.5 << True


def matrix_lshift_579():
    c579 = 1.5 << "ab"


def matrix_lshift_580():
    c580 = 1.5 << [1]


def matrix_lshift_581():
    c581 = 1.5 << (1,)


def matrix_lshift_582():
    c582 = 1.5 << {1}


def matrix_lshift_583():
    c583 = 1.5 << {"k": 1}


def matrix_lshift_584():
    c584 = 1.5 << None


def matrix_lshift_585():
    c585 = True << 3


def matrix_lshift_586():
    c586 = True << 1.5


def matrix_lshift_587():
    c587 = True << True


def matrix_lshift_588():
    c588 = True << "ab"


def matrix_lshift_589():
    c589 = True << [1]


def matrix_lshift_590():
    c590 = True << (1,)


def matrix_lshift_591():
    c591 = True << {1}


def matrix_lshift_592():
    c592 = True << {"k": 1}


def matrix_lshift_593():
    c593 = True << None


def matrix_lshift_594():
    c594 = "ab" << 3


def matrix_lshift_595():
    c595 = "ab" << 1.5


def matrix_lshift_596():
    c596 = "ab" << True


def matrix_lshift_597():
    c597 = "ab" << "ab"


def matrix_lshift_598():
    c598 = "ab" << [1]


def matrix_lshift_599():
    c599 = "ab" << (1,)


def matrix_lshift_600():
    c600 = "ab" << {1}


def matrix_lshift_601():
    c601 = "ab" << {"k": 1}


def matrix_lshift_602():
    c602 = "ab" << None


def matrix_lshift_603():
    c603 = [1] << 3


def matrix_lshift_604():
    c604 = [1] << 1.5


def matrix_lshift_605():
    c605 = [1] << True


def matrix_lshift_606():
    c606 = [1] << "ab"


def matrix_lshift_607():
    c607 = [1] << [1]


def matrix_lshift_608():
    c608 = [1] << (1,)


def matrix_lshift_609():
    c609 = [1] << {1}


def matrix_lshift_610():
    c610 = [1] << {"k": 1}


def matrix_lshift_611():
    c611 = [1] << None


def matrix_lshift_612():
    c612 = (1,) << 3


def matrix_lshift_613():
    c613 = (1,) << 1.5


def matrix_lshift_614():
    c614 = (1,) << True


def matrix_lshift_615():
    c615 = (1,) << "ab"


def matrix_lshift_616():
    c616 = (1,) << [1]


def matrix_lshift_617():
    c617 = (1,) << (1,)


def matrix_lshift_618():
    c618 = (1,) << {1}


def matrix_lshift_619():
    c619 = (1,) << {"k": 1}


def matrix_lshift_620():
    c620 = (1,) << None


def matrix_lshift_621():
    c621 = {1} << 3


def matrix_lshift_622():
    c622 = {1} << 1.5


def matrix_lshift_623():
    c623 = {1} << True


def matrix_lshift_624():
    c624 = {1} << "ab"


def matrix_lshift_625():
    c625 = {1} << [1]


def matrix_lshift_626():
    c626 = {1} << (1,)


def matrix_lshift_627():
    c627 = {1} << {1}


def matrix_lshift_628():
    c628 = {1} << {"k": 1}


def matrix_lshift_629():
    c629 = {1} << None


def matrix_lshift_630():
    c630 = {"k": 1} << 3


def matrix_lshift_631():
    c631 = {"k": 1} << 1.5


def matrix_lshift_632():
    c632 = {"k": 1} << True


def matrix_lshift_633():
    c633 = {"k": 1} << "ab"


def matrix_lshift_634():
    c634 = {"k": 1} << [1]


def matrix_lshift_635():
    c635 = {"k": 1} << (1,)


def matrix_lshift_636():
    c636 = {"k": 1} << {1}


def matrix_lshift_637():
    c637 = {"k": 1} << {"k": 1}


def matrix_lshift_638():
    c638 = {"k": 1} << None


def matrix_lshift_639():
    c639 = None << 3


def matrix_lshift_640():
    c640 = None << 1.5


def matrix_lshift_641():
    c641 = None << True


def matrix_lshift_642():
    c642 = None << "ab"


def matrix_lshift_643():
    c643 = None << [1]


def matrix_lshift_644():
    c644 = None << (1,)


def matrix_lshift_645():
    c645 = None << {1}


def matrix_lshift_646():
    c646 = None << {"k": 1}


def matrix_lshift_647():
    c647 = None << None


def matrix_rshift_648():
    c648 = 3 >> 3


def matrix_rshift_649():
    c649 = 3 >> 1.5


def matrix_rshift_650():
    c650 = 3 >> True


def matrix_rshift_651():
    c651 = 3 >> "ab"


def matrix_rshift_652():
    c652 = 3 >> [1]


def matrix_rshift_653():
    c653 = 3 >> (1,)


def matrix_rshift_654():
    c654 = 3 >> {1}


def matrix_rshift_655():
    c655 = 3 >> {"k": 1}


def matrix_rshift_656():
    c656 = 3 >> None


def matrix_rshift_657():
    c657 = 1.5 >> 3


def matrix_rshift_658():
    c658 = 1.5 >> 1.5


def matrix_rshift_659():
    c659 = 1.5 >> True


def matrix_rshift_660():
    c660 = 1.5 >> "ab"


def matrix_rshift_661():
    c661 = 1.5 >> [1]


def matrix_rshift_662():
    c662 = 1.5 >> (1,)


def matrix_rshift_663():
    c663 = 1.5 >> {1}


def matrix_rshift_664():
    c664 = 1.5 >> {"k": 1}


def matrix_rshift_665():
    c665 = 1.5 >> None


def matrix_rshift_666():
    c666 = True >> 3


def matrix_rshift_667():
    c667 = True >> 1.5


def matrix_rshift_668():
    c668 = True >> True


def matrix_rshift_669():
    c669 = True >> "ab"


def matrix_rshift_670():
    c670 = True >> [1]


def matrix_rshift_671():
    c671 = True >> (1,)


def matrix_rshift_672():
    c672 = True >> {1}


def matrix_rshift_673():
    c673 = True >> {"k": 1}


def matrix_rshift_674():
    c674 = True >> None


def matrix_rshift_675():
    c675 = "ab" >> 3


def matrix_rshift_676():
    c676 = "ab" >> 1.5


def matrix_rshift_677():
    c677 = "ab" >> True


def matrix_rshift_678():
    c678 = "ab" >> "ab"


def matrix_rshift_679():
    c679 = "ab" >> [1]


def matrix_rshift_680():
    c680 = "ab" >> (1,)


def matrix_rshift_681():
    c681 = "ab" >> {1}


def matrix_rshift_682():
    c682 = "ab" >> {"k": 1}


def matrix_rshift_683():
    c683 = "ab" >> None


def matrix_rshift_684():
    c684 = [1] >> 3


def matrix_rshift_685():
    c685 = [1] >> 1.5


def matrix_rshift_686():
    c686 = [1] >> True


def matrix_rshift_687():
    c687 = [1] >> "ab"


def matrix_rshift_688():
    c688 = [1] >> [1]


def matrix_rshift_689():
    c689 = [1] >> (1,)


def matrix_rshift_690():
    c690 = [1] >> {1}


def matrix_rshift_691():
    c691 = [1] >> {"k": 1}


def matrix_rshift_692():
    c692 = [1] >> None


def matrix_rshift_693():
    c693 = (1,) >> 3


def matrix_rshift_694():
    c694 = (1,) >> 1.5


def matrix_rshift_695():
    c695 = (1,) >> True


def matrix_rshift_696():
    c696 = (1,) >> "ab"


def matrix_rshift_697():
    c697 = (1,) >> [1]


def matrix_rshift_698():
    c698 = (1,) >> (1,)


def matrix_rshift_699():
    c699 = (1,) >> {1}


def matrix_rshift_700():
    c700 = (1,) >> {"k": 1}


def matrix_rshift_701():
    c701 = (1,) >> None


def matrix_rshift_702():
    c702 = {1} >> 3


def matrix_rshift_703():
    c703 = {1} >> 1.5


def matrix_rshift_704():
    c704 = {1} >> True


def matrix_rshift_705():
    c705 = {1} >> "ab"


def matrix_rshift_706():
    c706 = {1} >> [1]


def matrix_rshift_707():
    c707 = {1} >> (1,)


def matrix_rshift_708():
    c708 = {1} >> {1}


def matrix_rshift_709():
    c709 = {1} >> {"k": 1}


def matrix_rshift_710():
    c710 = {1} >> None


def matrix_rshift_711():
    c711 = {"k": 1} >> 3


def matrix_rshift_712():
    c712 = {"k": 1} >> 1.5


def matrix_rshift_713():
    c713 = {"k": 1} >> True


def matrix_rshift_714():
    c714 = {"k": 1} >> "ab"


def matrix_rshift_715():
    c715 = {"k": 1} >> [1]


def matrix_rshift_716():
    c716 = {"k": 1} >> (1,)


def matrix_rshift_717():
    c717 = {"k": 1} >> {1}


def matrix_rshift_718():
    c718 = {"k": 1} >> {"k": 1}


def matrix_rshift_719():
    c719 = {"k": 1} >> None


def matrix_rshift_720():
    c720 = None >> 3


def matrix_rshift_721():
    c721 = None >> 1.5


def matrix_rshift_722():
    c722 = None >> True


def matrix_rshift_723():
    c723 = None >> "ab"


def matrix_rshift_724():
    c724 = None >> [1]


def matrix_rshift_725():
    c725 = None >> (1,)


def matrix_rshift_726():
    c726 = None >> {1}


def matrix_rshift_727():
    c727 = None >> {"k": 1}


def matrix_rshift_728():
    c728 = None >> None


def matrix_and_729():
    c729 = 3 & 3


def matrix_and_730():
    c730 = 3 & 1.5


def matrix_and_731():
    c731 = 3 & True


def matrix_and_732():
    c732 = 3 & "ab"


def matrix_and_733():
    c733 = 3 & [1]


def matrix_and_734():
    c734 = 3 & (1,)


def matrix_and_735():
    c735 = 3 & {1}


def matrix_and_736():
    c736 = 3 & {"k": 1}


def matrix_and_737():
    c737 = 3 & None


def matrix_and_738():
    c738 = 1.5 & 3


def matrix_and_739():
    c739 = 1.5 & 1.5


def matrix_and_740():
    c740 = 1.5 & True


def matrix_and_741():
    c741 = 1.5 & "ab"


def matrix_and_742():
    c742 = 1.5 & [1]


def matrix_and_743():
    c743 = 1.5 & (1,)


def matrix_and_744():
    c744 = 1.5 & {1}


def matrix_and_745():
    c745 = 1.5 & {"k": 1}


def matrix_and_746():
    c746 = 1.5 & None


def matrix_and_747():
    c747 = True & 3


def matrix_and_748():
    c748 = True & 1.5


def matrix_and_749():
    c749 = True & True


def matrix_and_750():
    c750 = True & "ab"


def matrix_and_751():
    c751 = True & [1]


def matrix_and_752():
    c752 = True & (1,)


def matrix_and_753():
    c753 = True & {1}


def matrix_and_754():
    c754 = True & {"k": 1}


def matrix_and_755():
    c755 = True & None


def matrix_and_756():
    c756 = "ab" & 3


def matrix_and_757():
    c757 = "ab" & 1.5


def matrix_and_758():
    c758 = "ab" & True


def matrix_and_759():
    c759 = "ab" & "ab"


def matrix_and_760():
    c760 = "ab" & [1]


def matrix_and_761():
    c761 = "ab" & (1,)


def matrix_and_762():
    c762 = "ab" & {1}


def matrix_and_763():
    c763 = "ab" & {"k": 1}


def matrix_and_764():
    c764 = "ab" & None


def matrix_and_765():
    c765 = [1] & 3


def matrix_and_766():
    c766 = [1] & 1.5


def matrix_and_767():
    c767 = [1] & True


def matrix_and_768():
    c768 = [1] & "ab"


def matrix_and_769():
    c769 = [1] & [1]


def matrix_and_770():
    c770 = [1] & (1,)


def matrix_and_771():
    c771 = [1] & {1}


def matrix_and_772():
    c772 = [1] & {"k": 1}


def matrix_and_773():
    c773 = [1] & None


def matrix_and_774():
    c774 = (1,) & 3


def matrix_and_775():
    c775 = (1,) & 1.5


def matrix_and_776():
    c776 = (1,) & True


def matrix_and_777():
    c777 = (1,) & "ab"


def matrix_and_778():
    c778 = (1,) & [1]


def matrix_and_779():
    c779 = (1,) & (1,)


def matrix_and_780():
    c780 = (1,) & {1}


def matrix_and_781():
    c781 = (1,) & {"k": 1}


def matrix_and_782():
    c782 = (1,) & None


def matrix_and_783():
    c783 = {1} & 3


def matrix_and_784():
    c784 = {1} & 1.5


def matrix_and_785():
    c785 = {1} & True


def matrix_and_786():
    c786 = {1} & "ab"


def matrix_and_787():
    c787 = {1} & [1]


def matrix_and_788():
    c788 = {1} & (1,)


def matrix_and_789():
    c789 = {1} & {1}


def matrix_and_790():
    c790 = {1} & {"k": 1}


def matrix_and_791():
    c791 = {1} & None


def matrix_and_792():
    c792 = {"k": 1} & 3


def matrix_and_793():
    c793 = {"k": 1} & 1.5


def matrix_and_794():
    c794 = {"k": 1} & True


def matrix_and_795():
    c795 = {"k": 1} & "ab"


def matrix_and_796():
    c796 = {"k": 1} & [1]


def matrix_and_797():
    c797 = {"k": 1} & (1,)


def matrix_and_798():
    c798 = {"k": 1} & {1}


def matrix_and_799():
    c799 = {"k": 1} & {"k": 1}


def matrix_and_800():
    c800 = {"k": 1} & None


def matrix_and_801():
    c801 = None & 3


def matrix_and_802():
    c802 = None & 1.5


def matrix_and_803():
    c803 = None & True


def matrix_and_804():
    c804 = None & "ab"


def matrix_and_805():
    c805 = None & [1]


def matrix_and_806():
    c806 = None & (1,)


def matrix_and_807():
    c807 = None & {1}


def matrix_and_808():
    c808 = None & {"k": 1}


def matrix_and_809():
    c809 = None & None


def matrix_xor_810():
    c810 = 3 ^ 3


def matrix_xor_811():
    c811 = 3 ^ 1.5


def matrix_xor_812():
    c812 = 3 ^ True


def matrix_xor_813():
    c813 = 3 ^ "ab"


def matrix_xor_814():
    c814 = 3 ^ [1]


def matrix_xor_815():
    c815 = 3 ^ (1,)


def matrix_xor_816():
    c816 = 3 ^ {1}


def matrix_xor_817():
    c817 = 3 ^ {"k": 1}


def matrix_xor_818():
    c818 = 3 ^ None


def matrix_xor_819():
    c819 = 1.5 ^ 3


def matrix_xor_820():
    c820 = 1.5 ^ 1.5


def matrix_xor_821():
    c821 = 1.5 ^ True


def matrix_xor_822():
    c822 = 1.5 ^ "ab"


def matrix_xor_823():
    c823 = 1.5 ^ [1]


def matrix_xor_824():
    c824 = 1.5 ^ (1,)


def matrix_xor_825():
    c825 = 1.5 ^ {1}


def matrix_xor_826():
    c826 = 1.5 ^ {"k": 1}


def matrix_xor_827():
    c827 = 1.5 ^ None


def matrix_xor_828():
    c828 = True ^ 3


def matrix_xor_829():
    c829 = True ^ 1.5


def matrix_xor_830():
    c830 = True ^ True


def matrix_xor_831():
    c831 = True ^ "ab"


def matrix_xor_832():
    c832 = True ^ [1]


def matrix_xor_833():
    c833 = True ^ (1,)


def matrix_xor_834():
    c834 = True ^ {1}


def matrix_xor_835():
    c835 = True ^ {"k": 1}


def matrix_xor_836():
    c836 = True ^ None


def matrix_xor_837():
    c837 = "ab" ^ 3


def matrix_xor_838():
    c838 = "ab" ^ 1.5


def matrix_xor_839():
    c839 = "ab" ^ True


def matrix_xor_840():
    c840 = "ab" ^ "ab"


def matrix_xor_841():
    c841 = "ab" ^ [1]


def matrix_xor_842():
    c842 = "ab" ^ (1,)


def matrix_xor_843():
    c843 = "ab" ^ {1}


def matrix_xor_844():
    c844 = "ab" ^ {"k": 1}


def matrix_xor_845():
    c845 = "ab" ^ None


def matrix_xor_846():
    c846 = [1] ^ 3


def matrix_xor_847():
    c847 = [1] ^ 1.5


def matrix_xor_848():
    c848 = [1] ^ True


def matrix_xor_849():
    c849 = [1] ^ "ab"


def matrix_xor_850():
    c850 = [1] ^ [1]


def matrix_xor_851():
    c851 = [1] ^ (1,)


def matrix_xor_852():
    c852 = [1] ^ {1}


def matrix_xor_853():
    c853 = [1] ^ {"k": 1}


def matrix_xor_854():
    c854 = [1] ^ None


def matrix_xor_855():
    c855 = (1,) ^ 3


def matrix_xor_856():
    c856 = (1,) ^ 1.5


def matrix_xor_857():
    c857 = (1,) ^ True


def matrix_xor_858():
    c858 = (1,) ^ "ab"


def matrix_xor_859():
    c859 = (1,) ^ [1]


def matrix_xor_860():
    c860 = (1,) ^ (1,)


def matrix_xor_861():
    c861 = (1,) ^ {1}


def matrix_xor_862():
    c862 = (1,) ^ {"k": 1}


def matrix_xor_863():
    c863 = (1,) ^ None


def matrix_xor_864():
    c864 = {1} ^ 3


def matrix_xor_865():
    c865 = {1} ^ 1.5


def matrix_xor_866():
    c866 = {1} ^ True


def matrix_xor_867():
    c867 = {1} ^ "ab"


def matrix_xor_868():
    c868 = {1} ^ [1]


def matrix_xor_869():
    c869 = {1} ^ (1,)


def matrix_xor_870():
    c870 = {1} ^ {1}


def matrix_xor_871():
    c871 = {1} ^ {"k": 1}


def matrix_xor_872():
    c872 = {1} ^ None


def matrix_xor_873():
    c873 = {"k": 1} ^ 3


def matrix_xor_874():
    c874 = {"k": 1} ^ 1.5


def matrix_xor_875():
    c875 = {"k": 1} ^ True


def matrix_xor_876():
    c876 = {"k": 1} ^ "ab"


def matrix_xor_877():
    c877 = {"k": 1} ^ [1]


def matrix_xor_878():
    c878 = {"k": 1} ^ (1,)


def matrix_xor_879():
    c879 = {"k": 1} ^ {1}


def matrix_xor_880():
    c880 = {"k": 1} ^ {"k": 1}


def matrix_xor_881():
    c881 = {"k": 1} ^ None


def matrix_xor_882():
    c882 = None ^ 3


def matrix_xor_883():
    c883 = None ^ 1.5


def matrix_xor_884():
    c884 = None ^ True


def matrix_xor_885():
    c885 = None ^ "ab"


def matrix_xor_886():
    c886 = None ^ [1]


def matrix_xor_887():
    c887 = None ^ (1,)


def matrix_xor_888():
    c888 = None ^ {1}


def matrix_xor_889():
    c889 = None ^ {"k": 1}


def matrix_xor_890():
    c890 = None ^ None


def matrix_or_891():
    c891 = 3 | 3


def matrix_or_892():
    c892 = 3 | 1.5


def matrix_or_893():
    c893 = 3 | True


def matrix_or_894():
    c894 = 3 | "ab"


def matrix_or_895():
    c895 = 3 | [1]


def matrix_or_896():
    c896 = 3 | (1,)


def matrix_or_897():
    c897 = 3 | {1}


def matrix_or_898():
    c898 = 3 | {"k": 1}


def matrix_or_899():
    c899 = 3 | None


def matrix_or_900():
    c900 = 1.5 | 3


def matrix_or_901():
    c901 = 1.5 | 1.5


def matrix_or_902():
    c902 = 1.5 | True


def matrix_or_903():
    c903 = 1.5 | "ab"


def matrix_or_904():
    c904 = 1.5 | [1]


def matrix_or_905():
    c905 = 1.5 | (1,)


def matrix_or_906():
    c906 = 1.5 | {1}


def matrix_or_907():
    c907 = 1.5 | {"k": 1}


def matrix_or_908():
    c908 = 1.5 | None


def matrix_or_909():
    c909 = True | 3


def matrix_or_910():
    c910 = True | 1.5


def matrix_or_911():
    c911 = True | True


def matrix_or_912():
    c912 = True | "ab"


def matrix_or_913():
    c913 = True | [1]


def matrix_or_914():
    c914 = True | (1,)


def matrix_or_915():
    c915 = True | {1}


def matrix_or_916():
    c916 = True | {"k": 1}


def matrix_or_917():
    c917 = True | None


def matrix_or_918():
    c918 = "ab" | 3


def matrix_or_919():
    c919 = "ab" | 1.5


def matrix_or_920():
    c920 = "ab" | True


def matrix_or_921():
    c921 = "ab" | "ab"


def matrix_or_922():
    c922 = "ab" | [1]


def matrix_or_923():
    c923 = "ab" | (1,)


def matrix_or_924():
    c924 = "ab" | {1}


def matrix_or_925():
    c925 = "ab" | {"k": 1}


def matrix_or_926():
    c926 = "ab" | None


def matrix_or_927():
    c927 = [1] | 3


def matrix_or_928():
    c928 = [1] | 1.5


def matrix_or_929():
    c929 = [1] | True


def matrix_or_930():
    c930 = [1] | "ab"


def matrix_or_931():
    c931 = [1] | [1]


def matrix_or_932():
    c932 = [1] | (1,)


def matrix_or_933():
    c933 = [1] | {1}


def matrix_or_934():
    c934 = [1] | {"k": 1}


def matrix_or_935():
    c935 = [1] | None


def matrix_or_936():
    c936 = (1,) | 3


def matrix_or_937():
    c937 = (1,) | 1.5


def matrix_or_938():
    c938 = (1,) | True


def matrix_or_939():
    c939 = (1,) | "ab"


def matrix_or_940():
    c940 = (1,) | [1]


def matrix_or_941():
    c941 = (1,) | (1,)


def matrix_or_942():
    c942 = (1,) | {1}


def matrix_or_943():
    c943 = (1,) | {"k": 1}


def matrix_or_944():
    c944 = (1,) | None


def matrix_or_945():
    c945 = {1} | 3


def matrix_or_946():
    c946 = {1} | 1.5


def matrix_or_947():
    c947 = {1} | True


def matrix_or_948():
    c948 = {1} | "ab"


def matrix_or_949():
    c949 = {1} | [1]


def matrix_or_950():
    c950 = {1} | (1,)


def matrix_or_951():
    c951 = {1} | {1}


def matrix_or_952():
    c952 = {1} | {"k": 1}


def matrix_or_953():
    c953 = {1} | None


def matrix_or_954():
    c954 = {"k": 1} | 3


def matrix_or_955():
    c955 = {"k": 1} | 1.5


def matrix_or_956():
    c956 = {"k": 1} | True


def matrix_or_957():
    c957 = {"k": 1} | "ab"


def matrix_or_958():
    c958 = {"k": 1} | [1]


def matrix_or_959():
    c959 = {"k": 1} | (1,)


def matrix_or_960():
    c960 = {"k": 1} | {1}


def matrix_or_961():
    c961 = {"k": 1} | {"k": 1}


def matrix_or_962():
    c962 = {"k": 1} | None


def matrix_or_963():
    c963 = None | 3


def matrix_or_964():
    c964 = None | 1.5


def matrix_or_965():
    c965 = None | True


def matrix_or_966():
    c966 = None | "ab"


def matrix_or_967():
    c967 = None | [1]


def matrix_or_968():
    c968 = None | (1,)


def matrix_or_969():
    c969 = None | {1}


def matrix_or_970():
    c970 = None | {"k": 1}


def matrix_or_971():
    c971 = None | None
