"""Generator for the accept-side matrices: the operator pair table
(lhs tag x rhs tag x op family, one line per cell), the three-way
method-policy arms per builtin type, and the builtin-call battery.
Regenerate with `python3 gen_pairs.py`.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
H = "# generated by gen_pairs.py; regenerate rather than edit\n"

VALS = {
    "int": "3", "float": "1.5", "bool": "True", "str": '"ab"',
    "list": "[1]", "tuple": "(1,)", "set": "{1}",
    "dict": '{"k": 1}', "none": "None",
}

# One concrete witness for every builtin tag pair and supported operator.
# The regression runner executes every RHS with CPython and requires that
# completion to occur in the analyzer's (possibly broader) residual.
OPS = {"add": "+", "sub": "-", "mul": "*", "div": "/",
       "floordiv": "//", "mod": "%", "pow": "**",
       "lshift": "<<", "rshift": ">>", "and": "&", "xor": "^", "or": "|"}
TAGS = ["int", "float", "bool", "str", "list", "tuple", "set", "dict",
        "none"]


def binop_lines():
    lines, i = [], 0
    for op, sym in OPS.items():
        for lt in TAGS:
            for rt in TAGS:
                lines.extend([
                    f"def matrix_{op}_{i}():",
                    f"    c{i} = {VALS[lt]} {sym} {VALS[rt]}",
                    "",
                    "",
                ])
                i += 1
    return lines


# every modeled (tag, method) transfer rule, one call per line
METHOD_ARGS = {
    "list": [("append", "3"), ("clear", ""), ("copy", ""), ("count", "1"),
             ("extend", "[2]"), ("index", "1"), ("insert", "0, 9"),
             ("pop", ""), ("remove", "1"), ("reverse", ""), ("sort", "")],
    "dict": [("clear", ""), ("copy", ""), ("get", '"k"'), ("items", ""),
             ("keys", ""), ("pop", '"k"'), ("setdefault", '"k", 1'),
             ("update", "{}"), ("values", "")],
    "set": [("add", "3"), ("clear", ""), ("copy", ""), ("difference", "s2"),
            ("discard", "1"), ("intersection", "s2"), ("isdisjoint", "s2"),
            ("issubset", "s2"), ("issuperset", "s2"), ("pop", ""),
            ("remove", "1"), ("symmetric_difference", "s2"),
            ("union", "s2"), ("update", "s2")],
    "tuple": [("count", "1"), ("index", "1")],
    "range": [("count", "1"), ("index", "1")],
    "str": [("capitalize", ""), ("casefold", ""), ("center", "9"),
            ("count", '"a"'), ("endswith", '"a"'), ("expandtabs", ""),
            ("find", '"a"'), ("format", ""), ("index", '"a"'),
            ("isalnum", ""), ("isalpha", ""), ("isascii", ""),
            ("isdecimal", ""), ("isdigit", ""), ("isidentifier", ""),
            ("islower", ""), ("isnumeric", ""), ("isprintable", ""),
            ("isspace", ""), ("istitle", ""), ("isupper", ""),
            ("join", '["x"]'), ("ljust", "9"), ("lower", ""),
            ("lstrip", ""), ("removeprefix", '"a"'),
            ("removesuffix", '"b"'), ("replace", '"a", "b"'),
            ("rfind", '"a"'), ("rindex", '"a"'), ("rjust", "9"),
            ("rsplit", '","'), ("rstrip", ""), ("split", '","'),
            ("splitlines", ""), ("startswith", '"a"'), ("strip", ""),
            ("swapcase", ""), ("title", ""), ("upper", ""),
            ("zfill", "4")],
}
RECV = {"list": "xs", "dict": "d", "set": "s", "tuple": "t",
        "range": "rg", "str": "w"}


def method_lines():
    setup = {
        "list": ["xs = [1, 2]"],
        "dict": ['d = {"k": 1}'],
        "set": ["s = {1, 2}", "s2 = {2, 3}"],
        "tuple": ["t = (1, 2)"],
        "range": ["rg = range(4)"],
        "str": ['w = "aWb,c"'],
    }
    lines, i = [], 0
    for tag, ms in METHOD_ARGS.items():
        for m, a in ms:
            lines.append(f"def method_{tag}_{m}_{i}():")
            lines.extend(f"    {statement}" for statement in setup[tag])
            lines.extend([
                f"    m{i} = {RECV[tag]}.{m}({a})",
                "",
                "",
            ])
            i += 1
    return lines


THREEWAY = """def list_modeled():
    xs = [1, 2]
    m1 = xs.append(3)


def dict_modeled():
    d = {"k": 1}
    m2 = d.setdefault("k", 0)


def dict_opaque():
    d = {"k": 1}
    op1 = d.popitem()


def set_modeled():
    s = {1, 2}
    m3 = s.add(3)


def set_opaque():
    s = {1, 2}
    xs = [1, 2]
    op2 = s.difference_update(xs)


def str_modeled():
    t = "ab,cd"
    m4 = t.split(",")


def str_opaque():
    t = "ab,cd"
    op3 = t.partition(",")


def list_absent():
    xs = [1, 2]
    ab1 = xs.no_such_method()


def dict_absent():
    d = {"k": 1}
    ab2 = d.no_such_method()


def str_absent():
    t = "ab,cd"
    ab3 = t.no_such_method()


def deferred_method():
    d = {"k": 1}
    op1 = d.popitem()
    dfr = op1.mystery_method()


def deferred_binary():
    d = {"k": 1}
    op1 = d.popitem()
    dfb = op1 + 1
"""

BUILTINS = """xs = [3, 1]
n = len(xs)
rg = range(3)
print(n)
b = isinstance(xs, list)
it = iter(xs)
nx = next(it, 0)
l2 = list(rg)
t2 = tuple(xs)
s2 = set(xs)
d2 = dict()
sr = str(n)
rp = repr(xs)
"""


def main():
    body = "\n".join(binop_lines()).rstrip() + "\n"
    with open(os.path.join(HERE, "gp_binop_matrix.py"), "w") as f:
        f.write(H + body)
    with open(os.path.join(HERE, "gp_methods.py"), "w") as f:
        f.write(H + "\n".join(method_lines()).rstrip() + "\n")
    with open(os.path.join(HERE, "gp_threeway.py"), "w") as f:
        f.write(H + THREEWAY.rstrip() + "\n")
    with open(os.path.join(HERE, "gp_builtin_calls.py"), "w") as f:
        f.write(H + BUILTINS)
    print("wrote gp_binop_matrix.py gp_methods.py gp_threeway.py gp_builtin_calls.py")


if __name__ == "__main__":
    main()
