# Generated PyHard analysis. Original source line numbers are shown as L<n>.
# Every dispatch/type/shape claim lowers to assert followed by the same assume.
# Canonical machine-readable input: pyhard.analysis schema v1.
# L1 pyhard[summary membership_modes] returns={tuple}; escapes={}
def membership_modes(
    # L2 pyhard[type parameter] assert/assume conforms(needle, str); boundary nondet over 16 closed tags
    needle: str,
    # L3 pyhard[type parameter] assert/assume conforms(text, str); boundary nondet over 16 closed tags
    text: str,
    # L4 pyhard[type parameter] assert/assume conforms(items, list[str]); boundary nondet over 16 closed tags
    items: list[str],
    # L5 pyhard[type parameter] assert/assume conforms(table, dict[str, int]); boundary nondet over 16 closed tags
    table: dict[str, int],
) -> tuple[bool, bool, bool]:
    # L7 pyhard[flow membership_modes in] as_element -> (binding=definitely_unbound; tags={}; defs={unbound:as_element}), as_key -> (binding=definitely_unbound; tags={}; defs={unbound:as_key}), as_substring -> (binding=definitely_unbound; tags={}; defs={unbound:as_substring}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L7 pyhard[flow membership_modes out] as_element -> (binding=definitely_unbound; tags={}; defs={unbound:as_element}), as_key -> (binding=definitely_unbound; tags={}; defs={unbound:as_key}), as_substring -> (binding=definitely_bound; tags={bool}; defs={assignment:L7:C5}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L7 pyhard[read membership_modes.needle@20] binding=definitely_bound
    # L7 pyhard[read membership_modes.text@30] binding=definitely_bound
    # L7 pyhard[dispatch needle in text] assert/assume key in {str}
    # L7 pyhard[row {str}] exact_str_membership; result={bool}; specialized-by=membership operand contracts
    as_substring = needle in text
    # L8 pyhard[flow membership_modes in] as_element -> (binding=definitely_unbound; tags={}; defs={unbound:as_element}), as_key -> (binding=definitely_unbound; tags={}; defs={unbound:as_key}), as_substring -> (binding=definitely_bound; tags={bool}; defs={assignment:L7:C5}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L8 pyhard[flow membership_modes out] as_element -> (binding=definitely_bound; tags={bool}; defs={assignment:L8:C5}), as_key -> (binding=definitely_unbound; tags={}; defs={unbound:as_key}), as_substring -> (binding=definitely_bound; tags={bool}; defs={assignment:L7:C5}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L8 pyhard[read membership_modes.needle@18] binding=definitely_bound
    # L8 pyhard[read membership_modes.items@28] binding=definitely_bound
    # L8 pyhard[dispatch needle in items] assert/assume key in {list}
    # L8 pyhard[row {list}] call_contains_then_truth; owner=list; label=builtins.list.__contains__; plan=[receiver.__contains__:builtins.list.__contains__]; result={bool}
    as_element = needle in items
    # L9 pyhard[flow membership_modes in] as_element -> (binding=definitely_bound; tags={bool}; defs={assignment:L8:C5}), as_key -> (binding=definitely_unbound; tags={}; defs={unbound:as_key}), as_substring -> (binding=definitely_bound; tags={bool}; defs={assignment:L7:C5}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L9 pyhard[flow membership_modes out] as_element -> (binding=definitely_bound; tags={bool}; defs={assignment:L8:C5}), as_key -> (binding=definitely_bound; tags={bool}; defs={assignment:L9:C5}), as_substring -> (binding=definitely_bound; tags={bool}; defs={assignment:L7:C5}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L9 pyhard[read membership_modes.needle@14] binding=definitely_bound
    # L9 pyhard[read membership_modes.table@24] binding=definitely_bound
    # L9 pyhard[dispatch needle in table] assert/assume key in {dict}
    # L9 pyhard[row {dict}] exact_dict_membership; result={bool}; specialized-by=membership operand contracts
    as_key = needle in table
    # L10 pyhard[flow membership_modes in] as_element -> (binding=definitely_bound; tags={bool}; defs={assignment:L8:C5}), as_key -> (binding=definitely_bound; tags={bool}; defs={assignment:L9:C5}), as_substring -> (binding=definitely_bound; tags={bool}; defs={assignment:L7:C5}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L10 pyhard[flow membership_modes out:return] $result -> (binding=definitely_bound; tags={tuple}; defs={return}), as_element -> (binding=definitely_bound; tags={bool}; defs={assignment:L8:C5}), as_key -> (binding=definitely_bound; tags={bool}; defs={assignment:L9:C5}), as_substring -> (binding=definitely_bound; tags={bool}; defs={assignment:L7:C5}), items -> (binding=definitely_bound; tags={list}; defs={param:items}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), needle -> (binding=definitely_bound; tags={str}; defs={param:needle}), table -> (binding=definitely_bound; tags={dict}; defs={param:table}; points-to={alloc:L10:C12, alloc:L5:C17, alloc:L6:C12, boundary:external, boundary:membership_modes}), text -> (binding=definitely_bound; tags={str}; defs={param:text}); aliases may={items~table} must={}
    # L10 pyhard[read membership_modes.as_substring@12] binding=definitely_bound
    # L10 pyhard[read membership_modes.as_element@26] binding=definitely_bound
    # L10 pyhard[read membership_modes.as_key@38] binding=definitely_bound
    # L10 pyhard[type return] assert/assume conforms(result, tuple[bool, bool, bool]); observed={tuple}
    return as_substring, as_element, as_key
