# Generated PyHard analysis. Original source line numbers are shown as L<n>.
# Every dispatch/type/shape claim lowers to assert followed by the same assume.
# Canonical machine-readable input: pyhard.analysis schema v1.
# L1 pyhard[summary inspect_containers] returns={tuple}; escapes={IndexError, KeyError}
def inspect_containers(
    # L2 pyhard[type parameter] assert/assume conforms(values, list[int | str]); boundary nondet over 16 closed tags
    values: list[int | str],
    # L3 pyhard[type parameter] assert/assume conforms(lookup, dict[str, set[int]]); boundary nondet over 16 closed tags
    lookup: dict[str, set[int]],
    # L4 pyhard[type parameter] assert/assume conforms(pair, tuple[int, str]); boundary nondet over 16 closed tags
    pair: tuple[int, str],
) -> tuple[int | str, set[int], str]:
    # L6 pyhard[flow inspect_containers in] bucket -> (binding=definitely_unbound; tags={}; defs={unbound:bucket}), first -> (binding=definitely_unbound; tags={}; defs={unbound:first}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_unbound; tags={}; defs={unbound:second}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={lookup~pair, lookup~values, pair~values} must={}
    # L6 pyhard[flow inspect_containers out] bucket -> (binding=definitely_unbound; tags={}; defs={unbound:bucket}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_unbound; tags={}; defs={unbound:second}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={lookup~pair, lookup~values, pair~values} must={}
    # L6 pyhard[flow inspect_containers out:raise:IndexError] $exception -> (binding=definitely_bound; tags={IndexError}; defs={raise:IndexError}), bucket -> (binding=definitely_unbound; tags={}; defs={unbound:bucket}), first -> (binding=definitely_unbound; tags={}; defs={unbound:first}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_unbound; tags={}; defs={unbound:second}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={lookup~pair, lookup~values, pair~values} must={}
    # L6 pyhard[read inspect_containers.values@13] binding=definitely_bound
    # L6 pyhard[type subscript_key] assert/assume conforms(0, int | slice); observed={int}
    # L6 pyhard[dispatch values[0]] assert/assume key in {list}
    # L6 pyhard[row {list}] exact_list; result={bool, int, str}; raises={IndexError}; specialized-by=index and recursive type contracts
    first = values[0]
    # L7 pyhard[flow inspect_containers in] bucket -> (binding=definitely_unbound; tags={}; defs={unbound:bucket}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_unbound; tags={}; defs={unbound:second}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={lookup~pair, lookup~values, pair~values} must={}
    # L7 pyhard[flow inspect_containers out] bucket -> (binding=definitely_bound; tags={set}; defs={assignment:L7:C5}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_unbound; tags={}; defs={unbound:second}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={bucket~lookup, bucket~pair, bucket~values, lookup~pair, lookup~values, pair~values} must={}
    # L7 pyhard[flow inspect_containers out:raise:KeyError] $exception -> (binding=definitely_bound; tags={KeyError}; defs={raise:KeyError}), bucket -> (binding=definitely_unbound; tags={}; defs={unbound:bucket}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_unbound; tags={}; defs={unbound:second}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={lookup~pair, lookup~values, pair~values} must={}
    # L7 pyhard[read inspect_containers.lookup@14] binding=definitely_bound
    # L7 pyhard[type subscript_key] assert/assume conforms('numbers', str); observed={str}
    # L7 pyhard[dispatch lookup['numbers']] assert/assume key in {dict}
    # L7 pyhard[row {dict}] exact_dict; result={set}; raises={KeyError}; specialized-by=index and recursive type contracts
    bucket = lookup["numbers"]
    # L8 pyhard[flow inspect_containers in] bucket -> (binding=definitely_bound; tags={set}; defs={assignment:L7:C5}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_unbound; tags={}; defs={unbound:second}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={bucket~lookup, bucket~pair, bucket~values, lookup~pair, lookup~values, pair~values} must={}
    # L8 pyhard[flow inspect_containers out] bucket -> (binding=definitely_bound; tags={set}; defs={assignment:L7:C5}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_bound; tags={str}; defs={assignment:L8:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={bucket~lookup, bucket~pair, bucket~values, lookup~pair, lookup~values, pair~values} must={}
    # L8 pyhard[read inspect_containers.pair@14] binding=definitely_bound
    # L8 pyhard[type subscript_key] assert/assume conforms(1, int | slice); observed={int}
    # L8 pyhard[dispatch pair[1]] assert/assume key in {tuple}
    # L8 pyhard[row {tuple}] exact_tuple; result={str}; specialized-by=index and recursive type contracts
    second = pair[1]
    # L9 pyhard[flow inspect_containers in] bucket -> (binding=definitely_bound; tags={set}; defs={assignment:L7:C5}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_unbound; tags={}; defs={unbound:local}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_bound; tags={str}; defs={assignment:L8:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={bucket~lookup, bucket~pair, bucket~values, lookup~pair, lookup~values, pair~values} must={}
    # L9 pyhard[flow inspect_containers out] bucket -> (binding=definitely_bound; tags={set}; defs={assignment:L7:C5}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_bound; tags={list}; defs={assignment:L9:C5}; points-to={alloc:L9:C24}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_bound; tags={str}; defs={assignment:L8:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={bucket~local, bucket~lookup, bucket~pair, bucket~values, local~lookup, local~pair, local~values, lookup~pair, lookup~values, pair~values} must={}
    # L9 pyhard[type local_assignment] assert/assume conforms(local, list[int]); observed={list}
    local: list[int] = [1, 2, 3]
    # L10 pyhard[flow inspect_containers in] bucket -> (binding=definitely_bound; tags={set}; defs={assignment:L7:C5}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_bound; tags={list}; defs={assignment:L9:C5}; points-to={alloc:L9:C24}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_bound; tags={str}; defs={assignment:L8:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={bucket~local, bucket~lookup, bucket~pair, bucket~values, local~lookup, local~pair, local~values, lookup~pair, lookup~values, pair~values} must={}
    # L10 pyhard[flow inspect_containers out:return] $result -> (binding=definitely_bound; tags={tuple}; defs={return}), bucket -> (binding=definitely_bound; tags={set}; defs={assignment:L7:C5}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), first -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L6:C5}), local -> (binding=definitely_bound; tags={list}; defs={assignment:L9:C5}; points-to={alloc:L9:C24}), lookup -> (binding=definitely_bound; tags={dict}; defs={param:lookup}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), pair -> (binding=definitely_bound; tags={tuple}; defs={param:pair}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}), second -> (binding=definitely_bound; tags={str}; defs={assignment:L8:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L10:C12, alloc:L3:C18, alloc:L4:C17, alloc:L5:C12, alloc:L9:C24, boundary:external, boundary:inspect_containers}); aliases may={bucket~local, bucket~lookup, bucket~pair, bucket~values, local~lookup, local~pair, local~values, lookup~pair, lookup~values, pair~values} must={}
    # L10 pyhard[read inspect_containers.first@12] binding=definitely_bound
    # L10 pyhard[read inspect_containers.bucket@19] binding=definitely_bound
    # L10 pyhard[read inspect_containers.second@27] binding=definitely_bound
    # L10 pyhard[type return] assert/assume conforms(result, tuple[int | str, set[int], str]); observed={tuple}
    return first, bucket, second
