# Generated PyHard analysis. Original source line numbers are shown as L<n>.
# Every dispatch/type/shape claim lowers to assert followed by the same assume.
# Canonical machine-readable input: pyhard.analysis schema v1.
# L1 pyhard[summary first_or_unbound] returns={bool, int}; escapes={UnboundLocalError}
# L1 pyhard[type parameter] assert/assume conforms(values, list[int]); boundary nondet over 17 closed tags
def first_or_unbound(values: list[int]) -> int:
    # L2 pyhard[flow first_or_unbound in] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L2 pyhard[flow first_or_unbound out] missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L4:C5, unbound:missing}), result -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L3:C9, unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    try:
        # L3 pyhard[flow first_or_unbound in] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L3 pyhard[flow first_or_unbound out] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L3:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L3 pyhard[flow first_or_unbound out:raise:IndexError] $exception -> (binding=definitely_bound; tags={IndexError}; defs={raise:IndexError}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L3 pyhard[read first_or_unbound.values@18] binding=definitely_bound
        # L3 pyhard[type subscript_key] assert/assume conforms(0, int | slice); observed={int}
        # L3 pyhard[dispatch values[0]] assert/assume key in {list}
        # L3 pyhard[row {list}] exact_list; result={bool, int}; raises={IndexError}; specialized-by=index and recursive type contracts
        result = values[0]
    except IndexError as missing:
        # L5 pyhard[flow first_or_unbound in] missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L4:C5}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L5 pyhard[flow first_or_unbound out] missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L4:C5}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        pass
    # L6 pyhard[flow first_or_unbound in] missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L4:C5, unbound:missing}), result -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L3:C9, unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L6 pyhard[flow first_or_unbound out:raise:UnboundLocalError] $exception -> (binding=definitely_bound; tags={UnboundLocalError}; defs={raise:UnboundLocalError}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L4:C5, unbound:missing}), result -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L3:C9, unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L6 pyhard[flow first_or_unbound out:return] $result -> (binding=definitely_bound; tags={bool, int}; defs={return}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L4:C5, unbound:missing}), result -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L3:C9, unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L6 pyhard[read first_or_unbound.result@12] binding=maybe_bound; may raise UnboundLocalError
    # L6 pyhard[type return] assert/assume conforms(result, int); observed={bool, int}; evaluation may raise={UnboundLocalError}
    return result


# L9 pyhard[summary keep_old_on_failure] returns={bool, int, str}; escapes={}
# L9 pyhard[type parameter] assert/assume conforms(values, list[int]); boundary nondet over 17 closed tags
def keep_old_on_failure(values: list[int]) -> int | str:
    # L10 pyhard[flow keep_old_on_failure in] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L10 pyhard[flow keep_old_on_failure out] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_bound; tags={str}; defs={assignment:L10:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    result = "old"
    # L11 pyhard[flow keep_old_on_failure in] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_bound; tags={str}; defs={assignment:L10:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L11 pyhard[flow keep_old_on_failure out] missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L13:C5, unbound:missing}), result -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L10:C5, assignment:L12:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    try:
        # L12 pyhard[flow keep_old_on_failure in] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_bound; tags={str}; defs={assignment:L10:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L12 pyhard[flow keep_old_on_failure out] missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L12:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L12 pyhard[flow keep_old_on_failure out:raise:IndexError] $exception -> (binding=definitely_bound; tags={IndexError}; defs={raise:IndexError}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), result -> (binding=definitely_bound; tags={str}; defs={assignment:L10:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L12 pyhard[read keep_old_on_failure.values@18] binding=definitely_bound
        # L12 pyhard[type subscript_key] assert/assume conforms(0, int | slice); observed={int}
        # L12 pyhard[dispatch values[0]] assert/assume key in {list}
        # L12 pyhard[row {list}] exact_list; result={bool, int}; raises={IndexError}; specialized-by=index and recursive type contracts
        result = values[0]
    except IndexError as missing:
        # L14 pyhard[flow keep_old_on_failure in] missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L13:C5}), result -> (binding=definitely_bound; tags={str}; defs={assignment:L10:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        # L14 pyhard[flow keep_old_on_failure out] missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L13:C5}), result -> (binding=definitely_bound; tags={str}; defs={assignment:L10:C5}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
        pass
    # L15 pyhard[flow keep_old_on_failure in] missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L13:C5, unbound:missing}), result -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L10:C5, assignment:L12:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L15 pyhard[flow keep_old_on_failure out:return] $result -> (binding=definitely_bound; tags={bool, int, str}; defs={return}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L13:C5, unbound:missing}), result -> (binding=definitely_bound; tags={bool, int, str}; defs={assignment:L10:C5, assignment:L12:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure})
    # L15 pyhard[read keep_old_on_failure.result@12] binding=definitely_bound
    # L15 pyhard[type return] assert/assume conforms(result, int | str); observed={bool, int, str}
    return result


# L18 pyhard[summary keep_alias_on_failure] returns={list}; escapes={}
def keep_alias_on_failure(
    # L19 pyhard[type parameter] assert/assume conforms(original, list[int]); boundary nondet over 17 closed tags
    original: list[int],
    # L20 pyhard[type parameter] assert/assume conforms(candidates, list[list[int]]); boundary nondet over 17 closed tags
    candidates: list[list[int]],
) -> list[int]:
    # L22 pyhard[flow keep_alias_on_failure in] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}); aliases may={candidates~original} must={}
    # L22 pyhard[flow keep_alias_on_failure out] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={original~result}
    # L22 pyhard[read keep_alias_on_failure.original@14] binding=definitely_bound
    result = original
    # L23 pyhard[flow keep_alias_on_failure in] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={original~result}
    # L23 pyhard[flow keep_alias_on_failure out] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L25:C5, unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5, assignment:L24:C9}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={}
    try:
        # L24 pyhard[flow keep_alias_on_failure in] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={original~result}
        # L24 pyhard[flow keep_alias_on_failure out] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L24:C9}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={}
        # L24 pyhard[flow keep_alias_on_failure out:raise:IndexError] $exception -> (binding=definitely_bound; tags={IndexError}; defs={raise:IndexError}), candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={original~result}
        # L24 pyhard[read keep_alias_on_failure.candidates@18] binding=definitely_bound
        # L24 pyhard[type subscript_key] assert/assume conforms(0, int | slice); observed={int}
        # L24 pyhard[dispatch candidates[0]] assert/assume key in {list}
        # L24 pyhard[row {list}] exact_list; result={list}; raises={IndexError}; specialized-by=index and recursive type contracts
        result = candidates[0]
    except IndexError as missing:
        # L26 pyhard[flow keep_alias_on_failure in] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L25:C5}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={original~result}
        # L26 pyhard[flow keep_alias_on_failure out] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_bound; tags={IndexError}; defs={handler:L25:C5}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={original~result}
        pass
    # L27 pyhard[flow keep_alias_on_failure in] candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L25:C5, unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5, assignment:L24:C9}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={}
    # L27 pyhard[flow keep_alias_on_failure out:return] $result -> (binding=definitely_bound; tags={list}; defs={return}), candidates -> (binding=definitely_bound; tags={list}; defs={param:candidates}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), missing -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L25:C5, unbound:missing}), original -> (binding=definitely_bound; tags={list}; defs={param:original}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}), result -> (binding=definitely_bound; tags={list}; defs={assignment:L22:C5, assignment:L24:C9}; points-to={boundary:external, boundary:first_or_unbound, boundary:keep_alias_on_failure, boundary:keep_old_on_failure}); aliases may={candidates~original, candidates~result, original~result} must={}
    # L27 pyhard[read keep_alias_on_failure.result@12] binding=definitely_bound
    # L27 pyhard[type return] assert/assume conforms(result, list[int]); observed={list}
    return result
