# Generated PyHard analysis. Original source line numbers are shown as L<n>.
# Every dispatch/type/shape claim lowers to assert followed by the same assume.
# Canonical machine-readable input: pyhard.analysis schema v1.
class LoopError(Exception):
    pass


# L5 pyhard[summary break_from_handler] returns={bool, int}; escapes={}
# L5 pyhard[type parameter] assert/assume conforms(values, list[int]); boundary nondet over 17 closed tags
def break_from_handler(values: list[int]) -> int:
    # L6 pyhard[flow break_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={unbound:caught}), item -> (binding=definitely_unbound; tags={}; defs={unbound:item}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L6 pyhard[flow break_from_handler out] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L9:C9, unbound:caught}), item -> (binding=maybe_bound; tags={bool, int}; defs={iteration:L6:C9, unbound:item}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L10:C13, assignment:L13:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L6 pyhard[read break_from_handler.values@17] binding=definitely_bound
    # L6 pyhard[dispatch values] assert/assume key in {list}
    # L6 pyhard[row {list}] call_iter; owner=list; label=builtins.list.__iter__; plan=[receiver.__iter__:builtins.list.__iter__]
    for item in values:
        # L7 pyhard[flow break_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={unbound:caught}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
        # L7 pyhard[flow break_from_handler out:break] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L9:C9}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L10:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
        try:
            # L8 pyhard[flow break_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={unbound:caught}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
            # L8 pyhard[flow break_from_handler out:raise:LoopError] $exception -> (binding=definitely_bound; tags={LoopError}; defs={raise:LoopError}), caught -> (binding=definitely_unbound; tags={}; defs={unbound:caught}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
            raise LoopError()
        except LoopError as caught:
            # L10 pyhard[flow break_from_handler in] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L9:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            # L10 pyhard[flow break_from_handler out] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L9:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L10:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            # L10 pyhard[read break_from_handler.item@22] binding=definitely_bound
            result = item
            # L11 pyhard[flow break_from_handler in] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L9:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L10:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            # L11 pyhard[flow break_from_handler out:break] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L9:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L6:C9}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L10:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            break
    else:
        # L13 pyhard[flow break_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={unbound:caught}), item -> (binding=definitely_unbound; tags={}; defs={unbound:item}), result -> (binding=definitely_unbound; tags={}; defs={unbound:result}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
        # L13 pyhard[flow break_from_handler out] caught -> (binding=definitely_unbound; tags={}; defs={unbound:caught}), item -> (binding=definitely_unbound; tags={}; defs={unbound:item}), result -> (binding=definitely_bound; tags={int}; defs={assignment:L13:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
        # L13 pyhard[dispatch 0 - 1] assert/assume key in {(int, int)}
        # L13 pyhard[row {(int, int)}] binary_protocol; result={int}; terminal=certified_builtin_total
        result = 0 - 1
    # L14 pyhard[flow break_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L9:C9, unbound:caught}), item -> (binding=maybe_bound; tags={bool, int}; defs={iteration:L6:C9, unbound:item}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L10:C13, assignment:L13:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L14 pyhard[flow break_from_handler out:return] $result -> (binding=definitely_bound; tags={bool, int}; defs={return}), caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L9:C9, unbound:caught}), item -> (binding=maybe_bound; tags={bool, int}; defs={iteration:L6:C9, unbound:item}), result -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L10:C13, assignment:L13:C9}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L14 pyhard[read break_from_handler.result@12] binding=definitely_bound
    # L14 pyhard[type return] assert/assume conforms(result, int); observed={bool, int}
    return result


# L17 pyhard[summary continue_from_handler] returns={bool, int}; escapes={UnboundLocalError}
# L17 pyhard[type parameter] assert/assume conforms(values, list[int]); boundary nondet over 17 closed tags
def continue_from_handler(values: list[int]) -> int:
    # L18 pyhard[flow continue_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={unbound:caught}), item -> (binding=definitely_unbound; tags={}; defs={unbound:item}), last -> (binding=definitely_unbound; tags={}; defs={unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L18 pyhard[flow continue_from_handler out] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9, unbound:caught}), item -> (binding=maybe_bound; tags={bool, int}; defs={iteration:L18:C9, unbound:item}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L18 pyhard[read continue_from_handler.values@17] binding=definitely_bound
    # L18 pyhard[dispatch values] assert/assume key in {list}
    # L18 pyhard[row {list}] call_iter; owner=list; label=builtins.list.__iter__; plan=[receiver.__iter__:builtins.list.__iter__]
    for item in values:
        # L19 pyhard[flow continue_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9, unbound:caught}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
        # L19 pyhard[flow continue_from_handler out:continue] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L22:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
        try:
            # L20 pyhard[flow continue_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9, unbound:caught}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
            # L20 pyhard[flow continue_from_handler out:raise:LoopError] $exception -> (binding=definitely_bound; tags={LoopError}; defs={raise:LoopError}), caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9, unbound:caught}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
            raise LoopError()
        except LoopError as caught:
            # L22 pyhard[flow continue_from_handler in] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L21:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            # L22 pyhard[flow continue_from_handler out] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L21:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L22:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            # L22 pyhard[read continue_from_handler.item@20] binding=definitely_bound
            last = item
            # L23 pyhard[flow continue_from_handler in] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L21:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L22:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            # L23 pyhard[flow continue_from_handler out:continue] caught -> (binding=definitely_bound; tags={LoopError}; defs={handler:L21:C9}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}), item -> (binding=definitely_bound; tags={bool, int}; defs={iteration:L18:C9}), last -> (binding=definitely_bound; tags={bool, int}; defs={assignment:L22:C13}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external}); aliases may={caught~values} must={}
            continue
    # L24 pyhard[flow continue_from_handler in] caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9, unbound:caught}), item -> (binding=maybe_bound; tags={bool, int}; defs={iteration:L18:C9, unbound:item}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L24 pyhard[flow continue_from_handler out:raise:UnboundLocalError] $exception -> (binding=definitely_bound; tags={UnboundLocalError}; defs={raise:UnboundLocalError}), caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9, unbound:caught}), item -> (binding=maybe_bound; tags={bool, int}; defs={iteration:L18:C9, unbound:item}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L24 pyhard[flow continue_from_handler out:return] $result -> (binding=definitely_bound; tags={bool, int}; defs={return}), caught -> (binding=definitely_unbound; tags={}; defs={handler-cleanup:L21:C9, unbound:caught}), item -> (binding=maybe_bound; tags={bool, int}; defs={iteration:L18:C9, unbound:item}), last -> (binding=maybe_bound; tags={bool, int}; defs={assignment:L22:C13, unbound:last}), values -> (binding=definitely_bound; tags={list}; defs={param:values}; points-to={alloc:L20:C19, alloc:L8:C19, boundary:break_from_handler, boundary:continue_from_handler, boundary:external})
    # L24 pyhard[read continue_from_handler.last@12] binding=maybe_bound; may raise UnboundLocalError
    # L24 pyhard[type return] assert/assume conforms(result, int); observed={bool, int}; evaluation may raise={UnboundLocalError}
    return last
