"""Generate tests/comp.py: the comprehension interaction cross product.

Axes:
- source collection: list, set, tuple, dict (iterated by keys);
- destination: list, set, dict (the operation result as key), generator
  expression;
- filter: none, a non-narrowing predicate, an isinstance narrowing filter
  (only where a union makes narrowing meaningful), and an is-not-None band;
- element operation over: raw ints (operator), class field, monomorphic
  method, polymorphic method over a union, method over a union containing a
  class that lacks it, dataclass field, TypedDict literal key, tuple index,
  a user dunder.

Each unit has two checkpoints. The consumption checkpoint iterates an
identity comprehension of the source and applies the operation to its
elements: it tests that the destination's element edge carries exactly the
source precision, narrowed by the filter. The body checkpoint applies the
operation inside a second comprehension: it tests refinement through the
witness element. Expected residual statuses are derived from the axes: a
homogeneous receiver expects RESOLVED, an unfiltered union expects SPLIT(2),
a union with a missing method expects a value row plus an error row
(MAY_RAISE), and an isinstance filter restores RESOLVED. EXPECT records
(unit, line, kind, descriptor fragment, expected status) for the oracle.
"""

HEAD = '''"""Generated by comp_gen.py: do not edit."""
from dataclasses import dataclass
from typing import TypedDict


class Animal:
    def __init__(self, v: int):
        self.v = v

    def speak(self) -> str:
        return "a"


class Dog(Animal):
    def speak(self) -> str:
        return "woof"


class Cat(Animal):
    def speak(self) -> str:
        return "meow"


class Robot:
    def __init__(self):
        self.serial = 0


class W:
    def __init__(self, v: int):
        self.v = v


class A:
    def __init__(self, v: int):
        self.v = v

    def __add__(self, other):
        return A(self.v + other.v)


# frozen, because an unfrozen dataclass's generated __eq__ sets __hash__ = None
# and breaks the hash/eq contract -- which the admission checker rejects, so the
# whole corpus was inadmissible and its precision checkpoints unrunnable.
@dataclass(frozen=True)
class P:
    a: int
    b: str


class M(TypedDict):
    title: str
    year: int

'''

SRCS = {
    "li": ("[{items}]",),
    "se": ("{{{items}}}",),
    "tu": ("({items})",),
    "di": ("{{{pairs}}}",),
}

KINDS = {
    # name: (items, op(x), int_use(e), residual kind, desc fragment,
    #        allowed filters, allowed sources)
    "raw":  ("1, 2, 3", "({x} + 1)", "{e}", "binop", "Add",
             ["none", "pred"], ["li", "se", "tu", "di"]),
    "fld":  ("W(1), W(2)", "{x}.v", "{e}", "getattr", ".v",
             ["none", "pred"], ["li", "se", "tu", "di"]),
    "mono": ("Dog(1), Dog(2)", "{x}.speak()", "len({e})", "call", ".speak",
             ["none", "pred"], ["li", "se", "tu", "di"]),
    "poly": ("Dog(1), Cat(2)", "{x}.speak()", "len({e})", "call", ".speak",
             ["none", "pred", "isa"], ["li", "se", "tu", "di"]),
    "err":  ("Dog(1), Robot()", "{x}.speak()", "len({e})", "call", ".speak",
             ["none", "isa"], ["li", "se", "tu", "di"]),
    "dc":   ('P(1, "a"), P(2, "b")', "{x}.a", "{e}", "getattr", ".a",
             ["none", "pred"], ["li", "tu"]),
    "td":   ('M(title="x", year=1), M(title="y", year=2)',
             '{x}["title"]', "len({e})", "getitem", "[..]",
             ["none", "pred"], ["li", "tu"]),
    "tup":  ("(1, 2), (3, 4)", "{x}[0]", "{e}", "getitem", "[..]",
             ["none", "pred"], ["li", "se", "tu", "di"]),
    "dund": ("A(1), A(2)", "({x} + {x})", "({e}).v", "binop", "Add",
             ["none", "pred"], ["li", "se", "tu", "di"]),
}

PRED = {"raw": "{x} > 1", "fld": "{x}.v > 0", "mono": "{x}.v > 0",
        "poly": "{x}.v > 0", "dc": "{x}.a > 0", "td": '{x}["year"] > 0',
        "tup": "{x}[0] > 0", "dund": "{x}.v > 0"}

DSTS = ["ld", "sd", "dd", "gd"]


def expected(kind, filt):
    if kind == "poly":
        return "RESOLVED" if filt == "isa" else "SPLIT(2)"
    if kind == "err":
        return "RESOLVED" if filt == "isa" else "MAY_RAISE"
    return "RESOLVED"


def split_items(items):
    out, depth, cur = [], 0, ""
    for ch in items:
        if ch == "," and depth == 0:
            out.append(cur.strip())
            cur = ""
        else:
            if ch in "([{":
                depth += 1
            if ch in ")]}":
                depth -= 1
            cur += ch
    out.append(cur.strip())
    return [i for i in out if i]


def filt_src(kind, filt):
    if filt == "none":
        return ""
    if filt == "isa":
        return " if isinstance(x, Dog)"
    return " if " + PRED[kind].format(x="x")


def comp(dst, elt, filt):
    if dst == "ld":
        return f"[{elt} for x in src{filt}]"
    if dst == "sd":
        return f"{{{elt} for x in src{filt}}}"
    if dst == "dd":
        return f"{{{elt}: 0 for x in src{filt}}}"
    return f"({elt} for x in src{filt})"


def main():
    lines = HEAD.split("\n")
    expect = []
    names = []
    idx = 0
    for kind, (items, op, use, rk, frag, filts, srcs) in KINDS.items():
        for sk in srcs:
            for filt in filts:
                for dst in DSTS:
                    name = f"U{idx:03d}_{kind}_{sk}_{filt}_{dst}"
                    idx += 1
                    names.append(name)
                    exp = expected(kind, filt)
                    fs = filt_src(kind, filt)
                    if sk == "di":
                        srcexpr = SRCS[sk][0].format(
                            pairs=", ".join(i + ": 0"
                                            for i in split_items(items)))
                    else:
                        srcexpr = SRCS[sk][0].format(items=items)
                    lines.append(f"def {name}(k: int) -> int:")
                    lines.append(f"    src = {srcexpr}")
                    lines.append(f"    out = {comp(dst, 'x', fs)}")
                    lines.append("    acc = 0")
                    lines.append("    for y in out:")
                    opy = op.format(x="y")
                    cons_line = len(lines) + 1
                    lines.append(f"        acc = acc + {use.format(e=opy)}")
                    expect.append((name, cons_line, rk, frag, exp))
                    opx = op.format(x="x")
                    body_line = len(lines) + 1
                    lines.append(
                        f"    res = {comp(dst, use.format(e=opx), fs)}")
                    expect.append((name, body_line, rk, frag, exp))
                    if dst == "gd":
                        lines.append("    cnt = 0")
                        lines.append("    for z in res:")
                        lines.append("        cnt = cnt + 1")
                    else:
                        lines.append("    cnt = len(res)")
                    lines.append("    return acc + cnt")
                    lines.append("")
    # optional band: None in the source, with and without the guard
    for filt in ("none", "notnone"):
        for dst in DSTS:
            name = f"U{idx:03d}_opt_li_{filt}_{dst}"
            idx += 1
            names.append(name)
            fs = " if x is not None" if filt == "notnone" else ""
            exp = "RESOLVED" if filt == "notnone" else "MAY_RAISE"
            lines.append(f"def {name}(k: int) -> int:")
            lines.append("    src = [Dog(1), None]")
            lines.append(f"    out = {comp(dst, 'x', fs)}")
            lines.append("    acc = 0")
            lines.append("    for y in out:")
            cons_line = len(lines) + 1
            lines.append("        acc = acc + len(y.speak())")
            expect.append((name, cons_line, "call", ".speak", exp))
            body_line = len(lines) + 1
            lines.append(f"    res = {comp(dst, 'len(x.speak())', fs)}")
            expect.append((name, body_line, "call", ".speak", exp))
            if dst == "gd":
                lines.append("    cnt = 0")
                lines.append("    for z in res:")
                lines.append("        cnt = cnt + 1")
            else:
                lines.append("    cnt = len(res)")
            lines.append("    return acc + cnt")
            lines.append("")
    lines.append("")
    for n in names:
        lines += ["try:", f"    _o_{n} = {n}(0)", "except Exception:",
                  "    pass"]
    lines.append("")
    lines.append("EXPECT = " + repr(expect))
    lines.append("CASES = " + repr({n: [0] for n in names}))
    lines.append("")
    with open("tests/comp.py", "w") as f:
        f.write("\n".join(lines))
    print(f"wrote tests/comp.py: {len(names)} units, "
          f"{len(expect)} checkpoints")


if __name__ == "__main__":
    main()
