"""Generate tests/fuzz.py: seeded random compositions of control flow.

Each unit composes for, bounded while, if, try/except, try/else, try/finally
to depth 3 with random terminators (normal, break, continue, return, raise)
and randomly chosen handler classes that may or may not match what the body
raises, so exceptions sometimes escape, sometimes get caught, and sometimes
cross a finally that itself terminates.  While loops increment their counter
before the body so continue cannot diverge; every loop is bounded, so every
unit terminates concretely on every argument.
"""
import random

EXCS = ["ValueError", "KeyError", "Sig"]

HEAD = '''"""Generated by fuzz_gen.py: do not edit."""


class Sig(Exception):
    pass

'''


class Gen:
    def __init__(self, seed):
        self.r = random.Random(seed)
        self.n = 0

    def fresh(self):
        self.n += 1
        return f"w{self.n}"

    def term(self, in_loop):
        opts = ["acc = acc + 1", "return acc",
                f'raise {self.r.choice(EXCS)}("z")']
        if in_loop:
            opts += ["break", "continue"]
        return self.r.choice(opts)

    def block(self, depth, ind, in_loop):
        lines = []
        for _ in range(self.r.randint(1, 2)):
            kind = self.r.choice(
                ["mark", "guard", "for", "while", "te", "tf", "tef"]
                if depth > 0 else ["mark", "guard"])
            if kind == "mark":
                lines.append(f"{ind}acc = acc + {self.r.randint(1, 9)}")
            elif kind == "guard":
                lines.append(f"{ind}if k == {self.r.randint(0, 3)}:")
                lines.append(f"{ind}    {self.term(in_loop)}")
            elif kind == "for":
                v = self.fresh()
                lines.append(f"{ind}for {v} in [1, 2]:")
                lines += self.block(depth - 1, ind + "    ", True)
            elif kind == "while":
                v = self.fresh()
                lines.append(f"{ind}{v} = 0")
                lines.append(f"{ind}while {v} < 2:")
                lines.append(f"{ind}    {v} = {v} + 1")
                lines += self.block(depth - 1, ind + "    ", True)
            elif kind == "te":
                lines.append(f"{ind}try:")
                lines += self.block(depth - 1, ind + "    ", in_loop)
                lines.append(f"{ind}except {self.r.choice(EXCS)}:")
                lines.append(f"{ind}    acc = acc + 100")
            elif kind == "tf":
                lines.append(f"{ind}try:")
                lines += self.block(depth - 1, ind + "    ", in_loop)
                lines.append(f"{ind}finally:")
                lines.append(f"{ind}    acc = acc + 200")
            elif kind == "tef":
                lines.append(f"{ind}try:")
                lines += self.block(depth - 1, ind + "    ", in_loop)
                lines.append(f"{ind}except {self.r.choice(EXCS)}:")
                lines.append(f"{ind}    acc = acc + 100")
                lines.append(f"{ind}else:")
                lines.append(f"{ind}    acc = acc + 300")
                lines.append(f"{ind}finally:")
                lines.append(f"{ind}    acc = acc + 200")
        return lines


def main():
    g = Gen(11)
    parts = [HEAD]
    names = []
    for i in range(80):
        name = f"Z{i:02d}"
        names.append(name)
        lines = [f"def {name}(k: int) -> int:", "    acc = 0"]
        lines += g.block(3, "    ", False)
        lines += ["    return acc", "", ""]
        parts.append("\n".join(lines))
    drv = []
    for n in names:
        drv += ["try:", f"    _o_{n} = {n}(1)", "except Exception:", "    pass"]
    parts.append("\n".join(drv) + "\n")
    parts.append("\nCASES = " + repr({n: [0, 1, 2, 3] for n in names}) + "\n")
    with open("tests/fuzz.py", "w") as f:
        f.write("\n".join(parts))
    print(f"wrote tests/fuzz.py: {len(names)} units")


if __name__ == "__main__":
    main()
