"""Generator for the rejection corpus: one file per checker raise site,
context variants where a rule fires in more than one syntactic position,
accept-side twins (the nearest legal program, proving no over-reject),
and accumulation mixes. Regenerate with `python3 gen_reject.py`; files
are deterministic, so goldens stay stable.

Naming: gr_<site>.py rejected, gt_<twin>.py accepted, gm_<mix>.py
multi-violation.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))

H = "# generated by gen_reject.py; regenerate rather than edit\n"


def w(name, body):
    with open(os.path.join(HERE, name), "w") as f:
        f.write(H + body)


def infunc(code):
    ind = "\n".join("    " + ln if ln else "" for ln in code.split("\n"))
    return f"def wrapper(a: int) -> int:\n{ind}\n    return a\n\n\nr = wrapper(1)\n"


def inmethod(code):
    ind = "\n".join("        " + ln if ln else "" for ln in code.split("\n"))
    return (f"class Holder:\n    def go(self, a: int) -> int:\n{ind}\n"
            f"        return a\n\n\nh = Holder()\nr = h.go(1)\n")


# ---------------------------------------------------------------- sites
# (name, code, contexts). Context 'top' emits as-is; 'func'/'method'
# wrap. Every file is expected REJECTED.
SITES = [
    # unsupported-node family, one file per raise site
    ("un_const_bytes", 'x = b"raw"', ["top", "func"]),
    ("un_const_complex", "x = 1j", ["top"]),
    ("un_binop_matmul", "x = 1\ny = x @ x", ["top", "func"]),
    ("un_binop_shift", "x = 1 << 2", ["top"]),
    ("un_binop_bitand", "x = 1 & 2", ["top"]),
    ("un_cmp_is", "a = 1\nx = a is None", ["top", "func"]),
    ("un_cmp_isnot", "a = 1\nx = a is not None", ["top"]),
    ("un_slice", "xs = [1, 2, 3]\nys = xs[0:2]", ["top", "func"]),
    ("un_comp_target_tuple",
     "pairs = [(1, 2)]\nxs = [a for (a, b) in pairs]", ["top"]),
    ("un_expr_yield_expr",
     "def g(n: int):\n    got = yield n\n    return got\n\n\nit = g(1)",
     ["top"]),
    ("un_target_list", "[a, b] = [1, 2]", ["top"]),
    ("un_augop_shift", "x = 1\nx <<= 2", ["top"]),
    ("un_exceptstar",
     "try:\n    x = 1\nexcept* ValueError:\n    x = 2", ["top"]),
    ("un_raise_from",
     "err = ValueError()\nraise ValueError() from err", ["top"]),
    ("un_raise_nonname", "class NS:\n    pass\n\n\ndef f(ns):\n"
     "    raise ns.attr\n\n\nf(NS())", ["top"]),
    ("un_kwonly", "def f(a: int, *, k: int) -> int:\n    return a\n\n\n"
     "r = f(1, k=2)", ["top"]),
    ("un_typealias", "type Pair = tuple", ["top"]),
    # starred-arg, all seven sites
    ("st_call_star", "def f(a: int, b: int) -> int:\n    return a\n\n\n"
     "xs = [1, 2]\nr = f(*xs)", ["top"]),
    ("st_call_kwstar", "def f(a: int) -> int:\n    return a\n\n\n"
     "d = {}\nr = f(**d)", ["top"]),
    ("st_dict_splat", "a = {}\nb = {**a}", ["top"]),
    ("st_target_star", "xs = [1, 2, 3]\na, *b = xs", ["top"]),
    ("st_def_star", "def f(*args) -> int:\n    return 0\n\n\nr = f()",
     ["top"]),
    ("st_def_kwstar", "def f(**kw) -> int:\n    return 0\n\n\nr = f()",
     ["top"]),
    # shadowed-builtin, all six binding positions
    ("sh_assign", "list = 3", ["top", "func", "method"]),
    ("sh_param", "def f(dict: int) -> int:\n    return dict\n\n\nr = f(1)",
     ["top"]),
    ("sh_def", "def len(xs: list) -> int:\n    return 0\n\n\nr = len([])",
     ["top"]),
    ("sh_class", "class set:\n    pass", ["top"]),
    ("sh_handler", "try:\n    x = 1\nexcept ValueError as str:\n    x = 2",
     ["top"]),
    ("sh_comp_target", "xs = [1]\nys = [int for int in xs]", ["top"]),
    # class-body-stmt, five shapes
    ("cb_td_method", "from typing import TypedDict\n\n\n"
     "class M(TypedDict):\n    title: str\n\n    def touch(self) -> str:\n"
     "        return self.title", ["top"]),
    ("cb_field_default", "class C:\n    x: int = 3", ["top"]),
    ("cb_ann_nonname", "class C:\n    x: int\n\n    y[0]: int", ["top"]),
    ("cb_expr", "class C:\n    1 + 1", ["top"]),
    ("cb_stmt", "class C:\n    if True:\n        pass", ["top"]),
    # async, five constructs (await/for/with live inside async def, which
    # itself flags: accumulation inside one construct)
    ("as_def", "async def f():\n    return 1", ["top"]),
    ("as_inner", "async def f(xs):\n    async for x in xs:\n        pass\n"
     "    async with xs:\n        pass\n    await xs\n"
     "    return [x async for x in xs]", ["top"]),
    ("as_method", "class C:\n    async def m(self):\n        return 1",
     ["top"]),
    # import family
    ("im_plain", "import os", ["top"]),
    ("im_from", "from os import path", ["top"]),
    ("im_dataclasses_field", "from dataclasses import field", ["top"]),
    ("im_typing_any", "from typing import Any", ["top"]),
    # class-decorator, three shapes
    ("cd_nondataclass", "def deco(c):\n    return c\n\n\n@deco\n"
     "class C:\n    pass", ["top"]),
    ("cd_dataclass_kw", "from dataclasses import dataclass\n\n\n"
     "@dataclass(frozen=True, order=True)\nclass C:\n    x: int", ["top"]),
    ("cd_expr", "class NS:\n    pass\n\n\n@NS.deco\nclass C:\n    pass",
     ["top"]),
    # unfrozen, two spellings
    ("uf_bare", "from dataclasses import dataclass\n\n\n@dataclass\n"
     "class C:\n    x: int", ["top"]),
    ("uf_false", "from dataclasses import dataclass\n\n\n"
     "@dataclass(frozen=False)\nclass C:\n    x: int", ["top"]),
    # singletons not already covered one-per-file in reject_*.py get
    # representative extra spellings
    ("bb_getattr", "x = getattr", ["top", "func"]),
    ("bb_type", "t = type(3)", ["top"]),
    ("bb_super", "class C:\n    def m(self) -> int:\n"
     "        s = super()\n        return 0", ["top"]),
    ("bb_globals", "g = globals()", ["top"]),
    ("bb_vars", "v = vars()", ["top"]),
    ("ho_setattr_hook", "class C:\n    def __setattr__(self, n, v):\n"
     "        pass", ["top"]),
    ("ho_init_subclass", "class C:\n"
     "    def __init_subclass__(cls) -> None:\n        pass", ["top"]),
    ("rd_radd", "class C:\n    def __radd__(self, o):\n        return o",
     ["top"]),
    ("rd_iadd", "class C:\n    def __iadd__(self, o):\n        return o",
     ["top"]),
    ("he_eq_only", "class C:\n    def __eq__(self, o):\n"
     "        return True", ["top"]),
    ("he_hash_only", "class C:\n    def __hash__(self):\n"
     "        return 1", ["top"]),
]

# ------------------------------------------------------ accept twins
# The nearest LEGAL program to each rule; expected ACCEPTED. Proves the
# checker rejects the construct, not the neighborhood.
TWINS = [
    ("frozen_dataclass", "from dataclasses import dataclass\n\n\n"
     "@dataclass(frozen=True)\nclass C:\n    x: int\n\n\nc = C(3)"),
    ("eq_and_hash", "class C:\n    def __eq__(self, o):\n"
     "        return True\n\n    def __hash__(self):\n        return 1\n"
     "\n\nc = C()"),
    ("typing_whitelist", "from typing import Optional, TypedDict\n\n\n"
     "class M(TypedDict):\n    t: str\n\n\nm = M(t=\"x\")"),
    ("bare_except", "try:\n    x = 1\nexcept:\n    x = 2"),
    ("except_baseexception",
     "try:\n    x = 1\nexcept BaseException:\n    x = 2"),
    ("single_gen_comp", "xs = [1, 2]\nys = [x + 1 for x in xs]"),
    ("attr_named_list", "class C:\n    list: int\n\n    def __init__(self"
     ") -> None:\n        self.list = 1\n\n\nc = C()\nn = c.list"),
    ("method_named_builtin", "class C:\n    def count(self) -> int:\n"
     "        return 1\n\n\nc = C()\nn = c.count()"),
    ("dunder_ok", "class C:\n    def __init__(self) -> None:\n"
     "        self.x = 1\n\n    def __add__(self, o):\n        return self"
     "\n\n\nc = C() + C()"),
    ("uadd_ok", "x = +5\ny = -5"),
    ("unary_invert_ok", "x = ~5\ny = ~True"),
    ("chained_cmp", "a = 2\nok = 1 < a < 3"),
    ("aug_ok", "x = 1\nx += 2\nx *= 3"),
    ("kwargs_at_call", "def f(a: int, b: int) -> int:\n    return a + b\n"
     "\n\nr = f(a=1, b=2)"),
    ("raise_name_call", "class Boom(Exception):\n    pass\n\n\n"
     "def f(n: int) -> int:\n    if n < 0:\n        raise Boom(\"neg\")\n"
     "    return n\n\n\nr = f(1)"),
    ("docstrings", 'class C:\n    """doc"""\n\n    x: int\n\n'
     '    def __init__(self) -> None:\n        """doc"""\n'
     "        self.x = 1\n\n\nc = C()"),
    # constructs that looked rejectable but are deliberately in the
    # fragment; each twin exercises its semantics, not just admission
    ("fstring", 'n = 3\ns = f"n={n} end"\nu = s.upper()'),
    ("ternary", "a = 1\nx = a + 1 if a > 0 else a - 1\ny = x * 2"),
    ("genexp", "xs = [1, 2]\ng = (x + 1 for x in xs)\nn = next(g, 0)"),
    ("setcomp", "xs = [1, 2, 1]\ns = {x + 1 for x in xs}\ns.add(9)"),
    ("dictcomp", 'xs = [1, 2]\nd = {x: str(x) for x in xs}\n'
     'v = d.get(1, "none")'),
]

# --------------------------------------------------------------- mixes
# Multi-violation programs: the Validation applicative must surface all
# of them in one pass, including violations nested inside rejected
# constructs and after them.
MIXES = [
    ("nested_in_rejected", "def outer(a: int) -> int:\n"
     "    def inner(b):\n        list = eval(\"b\")\n        return list\n"
     "    return inner(a)\n\n\nr = outer(1)"),
    ("both_branches", "flag = True\nif flag:\n    import os\nelse:\n"
     "    x = lambda: 1"),
    ("after_first", "import os\nx = 1 @ 2\ny = [a for (a, b) in [(1, 2)]]"
     "\nz = getattr"),
    ("lambda_holding_eval", "f = lambda s: eval(s)"),
    ("class_soup", "class Meta(type):\n    async def m(self):\n"
     "        pass\n\n    x: int = 5\n\n    def __getattr__(self, n):\n"
     "        return n"),
]


def main():
    made = []
    for name, code, contexts in SITES:
        for cx in contexts:
            fn = f"gr_{name}.py" if cx == "top" else f"gr_{name}_{cx}.py"
            body = (code + "\n" if cx == "top"
                    else infunc(code) if cx == "func" else inmethod(code))
            w(fn, body)
            made.append(fn)
    for name, code in TWINS:
        w(f"gt_{name}.py", code + "\n")
        made.append(f"gt_{name}.py")
    for name, code in MIXES:
        w(f"gm_{name}.py", code + "\n")
        made.append(f"gm_{name}.py")
    print(f"wrote {len(made)} files")


if __name__ == "__main__":
    main()
