"""Generate tests/matrix.py: the unit-combination matrix.

Matrix A: wrapper x terminator inside a for-loop.
  wrappers: plain, tf (try/finally), te (try/except), tef
            (try/except/else/finally)
  terminators: normal, brk, cont, ret, rse (raise ValueError)
  Marker increments distinguish which blocks ran: body +1, except +200,
  else +300, finally +400.

Matrix B: generator interactions.
  return-as-stop, mid-yield raise, the next()+except StopIteration sentinel
  loop, next() past exhaustion, StopIteration raised in the body (PEP 479),
  yields under try/finally, a generator consumed by a comprehension.

Matrix C: exceptions as loop control.
  a signal class escaping nested loops, a signal hierarchy caught by its
  base, and a bounded retry loop driven by raise inside while True.

Each unit is a self-contained function of one int parameter; CASES maps the
unit name to the concrete arguments the differential oracle runs.
"""

MODES = {
    "normal": "acc = acc + 7",
    "brk": "break",
    "cont": "continue",
    "ret": "return acc",
    "rse": 'raise ValueError("t")',
}

HEAD = '''"""Generated by matrix_gen.py: do not edit."""


class Signal(Exception):
    pass


class Inner(Signal):
    pass


class Found(Exception):
    pass

'''


def unit_a(wrapper, mode):
    name = f"A_{wrapper}_{mode}"
    hit = MODES[mode]
    body = [f"def {name}(k: int) -> int:",
            "    acc = 0",
            "    for v in [10, 20, 30]:"]
    if wrapper == "plain":
        body += ["        if v == k:",
                 f"            {hit}",
                 "        acc = acc + 1"]
    elif wrapper == "tf":
        body += ["        try:",
                 "            if v == k:",
                 f"                {hit}",
                 "            acc = acc + 1",
                 "        finally:",
                 "            acc = acc + 400"]
    elif wrapper == "te":
        body += ["        try:",
                 "            if v == k:",
                 f"                {hit}",
                 "            acc = acc + 1",
                 "        except ValueError:",
                 "            acc = acc + 200"]
    elif wrapper == "tef":
        body += ["        try:",
                 "            if v == k:",
                 f"                {hit}",
                 "            acc = acc + 1",
                 "        except ValueError:",
                 "            acc = acc + 200",
                 "        else:",
                 "            acc = acc + 300",
                 "        finally:",
                 "            acc = acc + 400"]
    body += ["    return acc", "", ""]
    return name, "\n".join(body)


GEN_UNITS = '''
def g_ret(n: int):
    yield 1
    if n == 1:
        return
    yield 2


def g_raise(n: int):
    yield 1
    if n == 1:
        raise ValueError("mid")
    yield 2


def g_stop(n: int):
    yield 1
    if n == 1:
        raise StopIteration()
    yield 2


def g_fin(n: int):
    acc = [0]
    try:
        yield 1
        yield 2
    finally:
        acc[0] = acc[0] + 1


def B_for_ret(k: int) -> int:
    acc = 0
    for x in g_ret(k):
        acc = acc + x
    return acc


def B_for_raise(k: int) -> int:
    acc = 0
    for x in g_raise(k):
        acc = acc + x
    return acc


def B_next_sentinel(k: int) -> int:
    it = g_ret(k)
    acc = 0
    while True:
        try:
            x = next(it)
        except StopIteration:
            break
        acc = acc + x
    return acc


def B_next_unhandled(k: int) -> int:
    it = g_ret(1)
    a = next(it)
    b = next(it)
    c = next(it)
    return a + b + c


def B_pep479(k: int) -> int:
    acc = 0
    for x in g_stop(k):
        acc = acc + x
    return acc


def B_yield_finally(k: int) -> int:
    acc = 0
    for x in g_fin(k):
        acc = acc + x
    return acc


def B_gen_comp(k: int) -> int:
    ys = [x + 1 for x in g_ret(k)]
    return ys[0]


def C_signal_nested(k: int) -> int:
    hits = 0
    try:
        for a in [1, 2, 3]:
            for b in [1, 2, 3]:
                if a * b == k:
                    raise Found("x")
                hits = hits + 1
    except Found:
        return hits + 1000
    return hits


def C_signal_hierarchy(k: int) -> int:
    try:
        if k == 1:
            raise Inner("deep")
        return 5
    except Signal:
        return 6


def C_retry(k: int) -> int:
    tries = 3
    while True:
        try:
            if k > 0:
                k = k - 1
                raise KeyError("again")
            return tries
        except KeyError:
            tries = tries - 1
            if tries == 0:
                return 0
'''


def main():
    parts = [HEAD]
    names = []
    for w in ("plain", "tf", "te", "tef"):
        for m in MODES:
            n, src = unit_a(w, m)
            names.append(n)
            parts.append(src)
    parts.append(GEN_UNITS)
    names += ["B_for_ret", "B_for_raise", "B_next_sentinel",
              "B_next_unhandled", "B_pep479", "B_yield_finally", "B_gen_comp",
              "C_signal_nested", "C_signal_hierarchy", "C_retry"]
    cases = {n: [10, 20, 99] if n.startswith("A_") else [0, 1, 2]
             for n in names}
    cases["C_signal_nested"] = [4, 9, 100]
    cases["C_retry"] = [0, 1, 2]
    drv = ["", "# drivers: analyzed in-module so renders show every unit"]
    for n in names:
        drv += [f"try:", f"    _o_{n} = {n}(1)",
                "except Exception:", "    pass"]
    parts.append("\n".join(drv) + "\n")
    parts.append("\nCASES = " + repr(cases) + "\n")
    with open("tests/matrix.py", "w") as f:
        f.write("\n".join(parts))
    print(f"wrote tests/matrix.py: {len(names)} units")


if __name__ == "__main__":
    main()
