"""Generate tests/stress.py: the wide and deep stress suite.

Band S: outer loop (for, while) x wrapper (plain, tf, te, tef) x terminator
        (normal, brk, cont, ret, rse): 40 units.
Band F: the finally block itself terminates (break, continue, return,
        raise KeyError) over a pending exception: 4 units.
Band H: handwritten adversarial interactions: bare re-raise, handler raising
        a different exception, exception replacement in finally, nested
        rethrow, mutual recursion under annotations, generator of generators,
        yield from, early consumer break over a try/finally generator, a
        generator yielding from its own loop with break, nested
        comprehensions, comprehensions calling methods, a raising dunder, a
        dunder in a condition, a signal escaping a double while, chained
        comparison, augmented assignment, string operations, or-defaulting
        over None, an isinstance ladder, return in else, continue in except.

Each unit takes one int; CASES lists the concrete arguments.
"""

MODES = {"normal": "acc = acc + 7", "brk": "break", "cont": "continue",
         "ret": "return acc", "rse": 'raise ValueError("t")'}

HEAD = '''"""Generated by stress_gen.py: do not edit."""


class Sig(Exception):
    pass


class Deep(Sig):
    pass


class Cell:
    def __init__(self, v: int):
        self.v = v

    def val(self) -> int:
        return self.v

    def __add__(self, other):
        if self.v < 0:
            raise ValueError("neg")
        return Cell(self.v + other.v)

    def __eq__(self, other) -> bool:
        return self.v == other.v

'''


def unit_s(outer, wrapper, mode):
    name = f"S_{outer}_{wrapper}_{mode}"
    hit = MODES[mode]
    b = [f"def {name}(k: int) -> int:", "    acc = 0"]
    if outer == "for":
        b += ["    for v in [1, 2, 3]:"]
    else:
        b += ["    v = 0", "    while v < 3:", "        v = v + 1"]
    ind = "        " if outer == "for" else "        "
    if wrapper == "plain":
        b += [f"{ind}if v == k:", f"{ind}    {hit}", f"{ind}acc = acc + 1"]
    elif wrapper == "tf":
        b += [f"{ind}try:", f"{ind}    if v == k:", f"{ind}        {hit}",
              f"{ind}    acc = acc + 1",
              f"{ind}finally:", f"{ind}    acc = acc + 400"]
    elif wrapper == "te":
        b += [f"{ind}try:", f"{ind}    if v == k:", f"{ind}        {hit}",
              f"{ind}    acc = acc + 1",
              f"{ind}except ValueError:", f"{ind}    acc = acc + 200"]
    elif wrapper == "tef":
        b += [f"{ind}try:", f"{ind}    if v == k:", f"{ind}        {hit}",
              f"{ind}    acc = acc + 1",
              f"{ind}except ValueError:", f"{ind}    acc = acc + 200",
              f"{ind}else:", f"{ind}    acc = acc + 300",
              f"{ind}finally:", f"{ind}    acc = acc + 400"]
    b += ["    return acc", "", ""]
    return name, "\n".join(b)


def unit_f(fmode):
    name = f"F_{fmode}"
    hit = {"brk": "break", "cont": "continue",
           "ret": "return acc", "rse": 'raise KeyError("f")'}[fmode]
    b = [f"def {name}(k: int) -> int:",
         "    acc = 0",
         "    for v in [1, 2, 3]:",
         "        try:",
         "            if v == k:",
         '                raise ValueError("x")',
         "            acc = acc + 1",
         "        finally:",
         "            if v == 2:",
         f"                {hit}",
         "    return acc", "", ""]
    return name, "\n".join(b)


HAND = '''
def H_reraise(k: int) -> int:
    try:
        if k == 1:
            raise KeyError("a")
        return 1
    except KeyError:
        raise


def H_handler_raise(k: int) -> int:
    try:
        if k == 1:
            raise KeyError("a")
        return 1
    except KeyError:
        raise ValueError("swapped")


def H_finally_replace(k: int) -> int:
    try:
        if k == 1:
            raise KeyError("a")
        return 1
    finally:
        if k == 1:
            raise ValueError("replaced")


def H_nested_rethrow(k: int) -> int:
    try:
        try:
            if k == 1:
                raise Deep("d")
            return 1
        except Deep:
            raise
    except Sig:
        return 2


def is_even(n: int) -> bool:
    if n == 0:
        return True
    return is_odd(n - 1)


def is_odd(n: int) -> bool:
    if n == 0:
        return False
    return is_even(n - 1)


def H_mutual(k: int) -> int:
    if is_even(k):
        return 1
    return 0


def g_inner(k: int):
    yield 1
    yield 2


def g_outer(k: int):
    for x in g_inner(k):
        yield x + 10


def g_from(k: int):
    yield from g_inner(k)
    yield 3


def g_finloop(k: int):
    for v in [1, 2, 3]:
        try:
            yield v
        finally:
            if v == k:
                break


def H_gen_of_gen(k: int) -> int:
    acc = 0
    for x in g_outer(k):
        acc = acc + x
    return acc


def H_yield_from(k: int) -> int:
    acc = 0
    for x in g_from(k):
        acc = acc + x
    return acc


def H_gen_early_break(k: int) -> int:
    acc = 0
    for x in g_finloop(9):
        acc = acc + x
        if x == 2:
            break
    return acc


def H_comp_nested(k: int) -> int:
    ys = [y * 2 for y in [x + 1 for x in [1, 2, 3]]]
    return ys[0]


def H_comp_method(k: int) -> int:
    cs = [Cell(1), Cell(2)]
    vs = [c.val() for c in cs]
    return vs[0]


def H_dunder_raise(k: int) -> int:
    a = Cell(k - 1)
    b = Cell(2)
    c = a + b
    return c.v


def H_dunder_cond(k: int) -> int:
    a = Cell(k)
    b = Cell(1)
    if a == b:
        return 1
    return 0


def H_double_while_signal(k: int) -> int:
    hits = 0
    try:
        a = 0
        while a < 3:
            a = a + 1
            b = 0
            while b < 3:
                b = b + 1
                if a * b == k:
                    raise Sig("hit")
                hits = hits + 1
    except Sig:
        return hits + 1000
    return hits


def H_chain_cmp(k: int) -> int:
    if 1 < k < 3:
        return 1
    return 0


def H_aug(k: int) -> int:
    acc = 0
    for v in [1, 2, 3]:
        acc += v
        if v == k:
            acc += 100
    return acc


def H_str_ops(k: int) -> int:
    s = f"a-{k}-b"
    parts = s.split("-")
    t = parts[0].upper()
    return len(t)


def H_or_default(k: int) -> int:
    x = Cell(k) if k else None
    y = x or Cell(7)
    return y.val()


def H_isinstance_ladder(k: int) -> int:
    x = Cell(1) if k == 1 else ("s" if k == 2 else 3)
    if isinstance(x, Cell):
        return x.val()
    elif isinstance(x, str):
        return len(x)
    else:
        return x + 1


def H_try_else_ret(k: int) -> int:
    try:
        v = k + 1
    except Exception:
        return 0
    else:
        return v


def H_cont_in_except(k: int) -> int:
    acc = 0
    for v in [1, 2, 3]:
        try:
            if v == k:
                raise ValueError("c")
            acc = acc + 1
        except ValueError:
            continue
        acc = acc + 10
    return acc
'''


def main():
    parts = [HEAD]
    names = []
    for o in ("for", "wh"):
        for w in ("plain", "tf", "te", "tef"):
            for m in MODES:
                n, src = unit_s(o, w, m)
                names.append(n)
                parts.append(src)
    for fm in ("brk", "cont", "ret", "rse"):
        n, src = unit_f(fm)
        names.append(n)
        parts.append(src)
    parts.append(HAND)
    names += ["H_reraise", "H_handler_raise", "H_finally_replace",
              "H_nested_rethrow", "H_mutual", "H_gen_of_gen", "H_yield_from",
              "H_gen_early_break", "H_comp_nested", "H_comp_method",
              "H_dunder_raise", "H_dunder_cond", "H_double_while_signal",
              "H_chain_cmp", "H_aug", "H_str_ops", "H_or_default",
              "H_isinstance_ladder", "H_try_else_ret", "H_cont_in_except"]
    drv = ["", "# drivers: analyzed in-module so renders annotate every unit"]
    for n in names:
        drv += ["try:", f"    _o_{n} = {n}(1)", "except Exception:", "    pass"]
    parts.append("\n".join(drv) + "\n")
    cases = {n: [0, 1, 2, 3] for n in names}
    cases["H_double_while_signal"] = [4, 9, 100]
    cases["H_mutual"] = [0, 1, 4]
    parts.append("\nCASES = " + repr(cases) + "\n")
    with open("tests/stress.py", "w") as f:
        f.write("\n".join(parts))
    print(f"wrote tests/stress.py: {len(names)} units")


if __name__ == "__main__":
    main()
